### ISSUE TITLE
Xiaomi and Homey 1.5.0-rc.2

### ISSUE THREAD

**Issue by madmax75** [TedTolboom/com.xiaomi-mi-zigbee#1]
Is this version still working with Homey 1.5.0-rc.2?

**Comment by TedTolboom** [comment]
Hi Madmax,

Xiaomi Zigbee devices are changing the encryption keys after pairing. 

With this app, you will be able to get them paired (the right ID's are included), with some effort in keeping the devices awake, but currently Homey does not (yet) support exchanging the key... 

So no sensor data is received by Homey.

Focus from Athom is to first get Zigbee stable and further implemented. 

In the meantime, some developers (Bas Kiers) are working to get these devices working through the API, but this does require the Xiaomi Smart home hub.

**Comment by TedTolboom** [comment]
App has been released with Homey SW compatibility >=1.5.4
