### ISSUE TITLE
Unable to pair Aqara vibration sensor

### ISSUE THREAD

**Issue by jahnkenneth** [TedTolboom/com.xiaomi-mi-zigbee#100]
I am unable to pair the Aqara vibration sensor.
When starting the pairing, i press and hold the button on the sensor until the light blinks three times.
The process times out, and I get the message "No ZigBee device has been found."
Have tried three different sensors, a few centimeters from Homey.

Model: DJT11LM

**Comment by chinswain** [comment]
I had the same issue, try pressing the button repeatedly after holding it in for 5 seconds.

**Comment by jahnkenneth** [comment]
Thanks @chinswain :-)
I was able to get a step further, now it says "adding device", but it times out after a while - resulting in the same message... :-(

**Comment by Lansuper** [comment]
Same problem here with Homey 1.5.13-rc.11 and v0.4.2 of the Mi app with two vibration sensors.
Pressing it until LED blinks has no result. Pressing it a couple of times more until it blinks again makes Homey going into pairing mode. But at the end the vibration sensor isn't added.

**Comment by TedTolboom** [comment]
Can you try to, after holding the button for 5 seconds, keep pressing the button every 1-2 seconds until the inclusion is successfull?
The Zigbee inclusion process (from Homey) it quite slow... so in some cases the sensor will fall asleep...

**Comment by Reemster** [comment]
I had the same problem. If you indeed press 1/2sec everytime homey inclusion works. Maybe some extra information about this by the add screen in Homey? (i think you can close this isseu)

**Comment by jahnkenneth** [comment]
Got it paired now :-)

**Comment by TedTolboom** [comment]
@jahnkenneth thanks for the feedback. I'll see if I can update the pairing instructions / FAQ section of the community topic.

I'll close the issue, since resolved

**Comment by jasiek** [comment]
For a while, I couldn't figure out how to pair them - it is as easy as holding down the button until you see 3 or 4 blinks and leaving the sensor to pair. It will pair within half a minute or so.
