### ISSUE TITLE
Unknown zigbee device

### ISSUE THREAD

**Issue by ospectreo** [TedTolboom/com.xiaomi-mi-zigbee#101]
Trying to add a xiaomi or aqara device I get the same message.
"Unknown zigbee device"

I have two Homey devices
on both the same error for all this devices:

Door/Window sensor (MCCGQ01LM)
Wireless switch (WXKG01LM)
Aqara Window/Door Sensor (MCCGQ11LM)
Temperature/Humidity Sensor (WSDCGQ01LM)
Aqara Human Body Sensor (RTCGQ11LM)

**Comment by TedTolboom** [comment]
Are all these devices added as unknown Zigbee device??

Can you post a screenshot of the ID’s for each of the unknown devices?

**Comment by ospectreo** [comment]
> Are all these devices added as unknown Zigbee device??   -YES ALL OF THEM
> 
> Can you post a screenshot of the ID’s for each of the unknown devices?

What IDs are needed?

**Comment by TedTolboom** [comment]
The product ID, device ID and profile ID as can be found at devices > [unknown Zigbee device] > settings > device information

**Comment by TedTolboom** [comment]
And can you indicate which Xiaomi app version you have installed?

**Comment by ospectreo** [comment]
![ggg 2](https://user-images.githubusercontent.com/4184320/46910490-f84c9500-cf4d-11e8-8b19-7a1ac7d932cf.png)

**Comment by ospectreo** [comment]
![sss](https://user-images.githubusercontent.com/4184320/46910540-f59e6f80-cf4e-11e8-833f-77512a09e695.png)

**Comment by ospectreo** [comment]
![xiaomi](https://user-images.githubusercontent.com/4184320/46910552-22528700-cf4f-11e8-94dd-6eb080a75a21.png)

**Comment by ospectreo** [comment]
![ttt](https://user-images.githubusercontent.com/4184320/46910673-e15b7200-cf50-11e8-8914-d3ee9c577d4e.png)

**Comment by ospectreo** [comment]
![hhh](https://user-images.githubusercontent.com/4184320/46910724-2338e800-cf52-11e8-8421-dbbbba9e1f95.png)

**Comment by ospectreo** [comment]
![lll](https://user-images.githubusercontent.com/4184320/46910756-e3becb80-cf52-11e8-8a37-aa86ff8b0a34.png)

**Comment by ospectreo** [comment]
![ccc](https://user-images.githubusercontent.com/4184320/46910826-2d5be600-cf54-11e8-9ada-2354a55332ef.png)

**Comment by ospectreo** [comment]
It's enough?

**Comment by ospectreo** [comment]
![all](https://user-images.githubusercontent.com/4184320/46910875-2ed9de00-cf55-11e8-9697-0b8eed3c57ba.png)

**Comment by TedTolboom** [comment]
@ospectreo yes, thank you.
What you see if that the product ID is empty for all these devices.

During inclusion, completely handled by Homey's core firmware, the right app and device driver is chosen by matching the combination of product ID, device ID and profile ID to the ID's listed in the different apps.

In this case, for all these devices for some reason the product ID remains empty.

What you could do is try the following:

1. Disconnect Homey from it's power supply for 10 minutes.
2. Wait for 20 minutes so all apps are booted and are fully initialized.
3. Please check the product ID's shown for these devices... there have been reports before, that the product ID's now do show up... but the devices are still "Unknown Zigbee devices"
4. Remove all these devices from Homey by following the removal instructions (essential to do it with the device to reset it)
5. after that has been done, disconnect Homey from it's power supply for 10 minutes
6. wait again 20 minutes to boot and initialize all apps
7. try to include one of these devices by following the inclusion instructions **and** keeping the devices at short distance of Homey **and** awake every 1-2 seconds (by pressing the button)

Please let me know if this resolves your issue.

Reference Athom issue: https://github.com/athombv/homey/issues/2706

**Comment by Svensson78** [comment]
I tried this with my Cube but sadly still " unknown device"

Any other things to try?

**Comment by TedTolboom** [comment]
@ospectreo can you contribute to https://github.com/athombv/homey/issues/2706 to make Athom aware more people are suffering from this issue?

Thanks.

**Comment by ospectreo** [comment]
I still have not solved this problem there was no time to check

**Comment by ospectreo** [comment]
Today I updated homey to the latest version (1.5.13) but the problem did not disappear
Still can not connect all my xiaomi devices
Although they connect to the xiaomi hub without problems in one second

**Comment by ospectreo** [comment]
And I have two homey
and on both the same problem with xiaomi
<img width="401" alt="2018-11-27 21 51 50" src="https://user-images.githubusercontent.com/4184320/49107835-6693af80-f28f-11e8-8a49-114123010199.png">

**Comment by jtebbens** [comment]
Yeah also face exact same issue. Unknown Zigbee Device upon adding Xiaomi sensors. These worked before without issue. I had to remove them and re-add and now they show as Unknown.....funny. Restart and p2p done without result.

**Comment by vandernorth** [comment]
Since the last firmware upgrade (v2.1.2) I've been able to connect my motion, temperature, vibration and door sensors without too much problems (pairing failed due too timeout or unknown shepherd device a few times). Wireless double switch works as well. So far so good 👍
