### ISSUE TITLE
Add support  for new Aqara bulb zigbee version

### ISSUE THREAD

**Issue by LyoshaDovolen** [TedTolboom/com.xiaomi-mi-zigbee#107]
[aliexpress.com/item/mi-aqara-zigbee/32956347602.html](https://www.aliexpress.com/item/Original-xiaomi-mijia-aqara-bulb-zigbee-version-work-with-mi-home-app-and-for-apple-homekit/32956347602.html)

**Comment by TedTolboom** [comment]
Will be added in v0.5.3
