### ISSUE TITLE
I have only luminance change by motion detection. Human body sensor.

### ISSUE THREAD

**Issue by rowins** [TedTolboom/com.xiaomi-mi-zigbee#108]
Homey version: 1.5.13
Xiaomi aquara version: 0.4.3

It's not a big issue, but I was wondering if i'm the only one with this. My human body sensor change only the luminance when he detects motion. Is it possible for my sensor to actively change my luminance or at some time or when a flow triggers the sensor looks at what is the luminance at that moment.

Sorry for my bad English!

Thanks

**Comment by rowins** [comment]
I have already the answer.
Page 12, question. Page 13, answer.
https://forum.athom.com/discussion/4120/app-xiaomi-mi-zigbee-main-discussion-topic-v0-4-1/p12

**Comment by Thenorneron** [comment]
I have same issue. I can't open forum link. Can you tell me the solution for measuring luminance? Or maybe copy paste it? Thanks!

**Comment by rowins** [comment]
Yeah ofcourse. 

The question: Do you know if it's a device behaviour or app behaviour to only update luminance when motion is detected? 

Answer of developer:
 yes this is a device limitation. I did not find a solution / option yet to get independent luminance reports.

So there is no solution yet :(
