### ISSUE TITLE
Switch doesn't activate flow.

### ISSUE THREAD

**Issue by Mustang1966** [TedTolboom/com.xiaomi-mi-zigbee#109]
The Aqara switch (WXKG11LM) didn't work anymore on 2.0 RC1. I removed it and added again.

When i create a flow with button pressed then ... does not trigger the flow.

**Comment by FrankBakermans** [comment]
I have the same issue with the aqara wireless switch (Gyro). While you are looking into this issue, can you maybe add some new features like double click and long press? 

Cheers, Frank

**Comment by rvliege** [comment]
Seems to be the case for me although a v1 of the switch doesn't do anything. And 1 of my 2 v2 switches doesn't get the long press.

**Comment by TedTolboom** [comment]
Announced to be fixed in 2.0.0-rc.4.
Once I verified that it is fixed, I will close this issue

**Comment by TedTolboom** [comment]
@brtws it is not completely solved in rc8.
There is still a bug with re-using flows and changing the triggers. Try to create a new flow for this device and see if it is working.

Which device are we talking about?

**Comment by brtwrs** [comment]
I just created a new flow with the switch (WXKG11LM) as a trigger.. still nothing

**Comment by TedTolboom** [comment]
@brtwrs It should be resolved for rc.9. 

Can you confirm?

**Comment by brtwrs** [comment]
Yes it works again! Thanks Ted for your support and time:)

**Comment by TedTolboom** [comment]
I will close this issue; original issue has been resolved.

@jeroenspruijt if you still perceive an issue, please report it as seperate
