### ISSUE TITLE
Homey iPhone app crashes when changing temperature offset

### ISSUE THREAD

**Issue by mhoogenbosch** [TedTolboom/com.xiaomi-mi-zigbee#111]
When trying to change the offset of the temperature the iPhone honey app crashes. Some other settings are not readable but work.

**Comment by TedTolboom** [comment]
Known issue, verified with Athom, with 2.0.0-rc.4.
Any Z-wave or Zigbee app have this issue; including the Fibaro app.

I can’t fix this issue.
Will close this issue for now
