### ISSUE TITLE
Homey 2.0 rc4: Vibration sensor tilt angles not updating

### ISSUE THREAD

**Issue by psy0rz** [TedTolboom/com.xiaomi-mi-zigbee#112]
When i view the alarm and tilt status page of the device, the numbers aren't updating.

The alarm boolean have no problems.

The https://developer.athom.com/tools/devices page updates all values correctly.

**Comment by hive** [comment]
Im sure you are aware - but just in case, this is still occuring in v2-rc11. 

Would it perhaps help if myself/others also submitted a ticket to Athom support and if so - what is the actual issue we should describe so it doesnt get kicked back to you?

Thanks

**Comment by TedTolboom** [comment]
Can you confirm that this issue has been resolved in the latest releases?

**Comment by hive** [comment]
I can confirm that the tilt alarm is now working correctly (tested with 0.5.1)

Thank you

**Comment by psy0rz** [comment]
can also confirm it works! thanks for the effort!
