### ISSUE TITLE
Homey 2.0: Show temperature values overview screen.

### ISSUE THREAD

**Issue by psy0rz** [TedTolboom/com.xiaomi-mi-zigbee#113]
It would be nice if the temp and humidity is shown in the overview screen of the homey app. Now you have to long-click to see the values.

**Comment by TedTolboom** [comment]
Can you clarify what you mean (where exactly) with showing the data on the overview screen of the Homey app?

**Comment by mhoogenbosch** [comment]
I think he means on the devices screen. 
![tempsensor](https://user-images.githubusercontent.com/36899598/50138942-80c61980-02a0-11e9-8cc3-a5401474fd82.jpeg)

Something like this. Don't know if that is something an App can arrange. Same goes for pushing through the values to HomeKit. Currently that doesn't happen (which is different behaviour compared to 1.5).

**Comment by psy0rz** [comment]
Yeah thats exactly what i mean.

**Comment by TedTolboom** [comment]
I can't solve this in the app (alone). Athom limited this circle only to the thermostat devices.

Athom will need to solve this feature request in the 2.0.0 app.
Leading issue: https://github.com/athombv/homey-apps-sdk-issues/issues/17

**Comment by TedTolboom** [comment]
As mentioned above, I can't fullfill this request without Athom making a change. 
Please contact Athom support to change their mind.

I will close this issue for now.

**Comment by psy0rz** [comment]
thanks!
