### ISSUE TITLE
Homey 2.0 rc4: Vibration sensor advanced settings crash app.

### ISSUE THREAD

**Issue by psy0rz** [TedTolboom/com.xiaomi-mi-zigbee#114]
When i try to reset the tilt angle or other advanced settings, the homey app crashes.

**Comment by TedTolboom** [comment]
This is a Homey SW issue; for version 2.0.0 or corresponding app. 

There is nothing I can change / do about this (known) issue.

Please report to Athom through the proposed channel as described on firmware.athom.com

I will close this issue for now.
If Athom is redirecting you back to the community app developer, please let me know.
