### ISSUE TITLE
Advanced settings not readable

### ISSUE THREAD

**Issue by mhoogenbosch** [TedTolboom/com.xiaomi-mi-zigbee#115]
Don't know if this is a setting controlled by the app but the advanced settings are not readable in v2.0.0.

See screenshot of what I mean:

![advancedsettings](https://user-images.githubusercontent.com/36899598/50139281-83753e80-02a1-11e9-99ff-a8c87df0ce99.jpeg)

**Comment by TedTolboom** [comment]
Will be fixed in next 2.0.0-rc

**Comment by TedTolboom** [comment]
This is an issue within the 2.0.0 app.

I've created an issue in the homey-apps-sdk, to get it resolved:
https://github.com/athombv/homey-apps-sdk-issues/issues/26

For now, I will not change the Xiaomi app; Athom will need to solve this in the 2.0.0 app.

**Comment by TedTolboom** [comment]
Has been fixed in the 2.0.0 app; 
in a next update I'll shorten the text a bit further for readability.
