### ISSUE TITLE
Cannot find Aqara Motion Sensor and Occupancy Sensor for pairing

### ISSUE THREAD

**Issue by JustThe2ofUs** [TedTolboom/com.xiaomi-mi-zigbee#117]
Both devices can be selected to Add; unfortunately Homey doesn’t find them then, though pairing routine on the devices itself get started by the 3 sec push of the buttons. ?

**Comment by TedTolboom** [comment]
@justthe2ofus can you try the following.

* Restart Homey, 
* wait at least 30 minutes after restart for all apps to have initialized
* check at developer tools (https://developer.athom.com/tools/zigbee that the Zigbee network is up
* try to include the device at close proximity of Homey
* follow the instructions how to activate the inclusion mode, and once the inclusion process starts, keep the device awake by pressing the button / pinhole once event 1 - 2 seconds

If that doesn’t work, please provide more information on which other Zigbee devices you use

**Comment by JustThe2ofUs** [comment]
Hi Ted, thx for taking care. 
I feel like Athom should consider starting an AppStore where you can buy Apps like yours, as the effort you dev-guys make is incredible and should be more valued - but that’s OT. 

I tried your tips several times but unfortunately it doesn’t work out. I am using the door / window sensors and temperature sensors of Aqara w/ ZigBee; though battery level isn’t displayed the sensors pair pretty quickly and work w/o any issues. 
As I am just a “user”: Would it help to provide you w/ some logfile or something?

**Comment by soerensteen** [comment]
I am experiencing the same issue. No luck pairing a new Aqara Motion Sensor. Tried PTP, restart etc.

**Comment by JustThe2ofUs** [comment]
Hi, now all Vibration sensors and movement sensors are paired and do work as long as Diva Misses Homey has a good day...

Ensure you’re running the latest version of Homey firmware and the Xiaomi App. 
Then be close at Homey (a couple of metres in same room works fine) and start the pairing via the App. 
Then home down the button on the device until the blue light starts flashing (it will flash not only three times but 3000 times - just for as long as you don’t release the button). 
After it flashed 3 or 4 times just release your finger from the button for around 0,5 or max 1 second - and then just press the button again and then consequently every 1-2 seconds. 

To me it was important, that once it flashed 3,4 or even 5 times and I then released the button - i recognised there will be short flickering of the light. That seems to ruin the whole process. 
So take care about after releasing the button for the first time, start pressing the button again BEFORE it flickers the first time. 
That made it work for me.

**Comment by mauricesundermann** [comment]
I had the same problem. The solution of JustThe2ofUs is working for me. Thanks!
