### ISSUE TITLE
Xiaomi hunan body sensor

### ISSUE THREAD

**Issue by giocoo** [TedTolboom/com.xiaomi-mi-zigbee#118]
Update:
I restarted Homey for second time and now it works. I  also kept pushing the button more frequently than before. Maybe that’s why it worked. Problem solved.  

Homey 2.0. What ever I try, i can’t setup a connection. Homey seems to react because the text “add device” appears, but after that nothing happenes. I keep pushing the connection button during pairing. What else can I do?

**Comment by JustThe2ofUs** [comment]
Sounds like my issue as well 😁🤷‍♂️🤷‍♂️

**Comment by TedTolboom** [comment]
@giocoo thanks for the update; good to hear it worked.

**Comment by giocoo** [comment]
Hi Ted,

Is it true that I can’t select tags at the temperature sensor of xiaomi zigbee? I want to create a flow that tells me what the current temperature is when i ask for that.

Kind regards,

Giovanni

Verstuurd vanaf mijn iPad

Op 28 dec. 2018 om 20:10 heeft dT <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@giocoo<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgiocoo&data=02%7C01%7C%7Cabf2a90b697b4ea2bb2c08d66cf8169c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636816210109560624&sdata=Mb4k6iW0YoTm72HojYyUduEj1vsXpFyzpxOBSDVWOb0%3D&reserved=0> thanks for the update; good to hear it worked.
