### ISSUE TITLE
Slow response & no battery info

### ISSUE THREAD

**Issue by YD85** [TedTolboom/com.xiaomi-mi-zigbee#120]
Motion sensors are very slow to respond. So when I’m already way past the sensor lights go on. 
Also there is no battery info for any device.

**Comment by YD85** [comment]
Sorry: 50ce2181-2b5c-406a-82ac-e292e841cfe6

Thanks for looking into this

**Comment by TedTolboom** [comment]
@YD85 I didn't receive a crash log with that ID
