### ISSUE TITLE
Can’t change humidity value in flow

### ISSUE THREAD

**Issue by Egberjo** [TedTolboom/com.xiaomi-mi-zigbee#121]
@TedTolboom. I want to make a flow to switch off my bathroom fan when the humidity level has reached the value of 40% but I am not able to change the example level of 35%.
How can I resolve this?

**Comment by TedTolboom** [comment]
@Egberjo that is an issue of the new Next Gen app... 
As app developer I can only provide the initial example value. The Next Gen app should offer the option to change is..

Please contact Athom support to raise this issue, ok?

I'll close this issue (out of my control).
