### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by damianxd** [TedTolboom/com.xiaomi-mi-zigbee#123]
The aqara app doesn't start and it gives this error:
62aa2407-72d1-4062-af36-2f8bc0766f82

What should I do?

**Comment by TedTolboom** [comment]
Can you help me with some more information?

For reference, the crash report received:

> A crash occurred for your app (version 0.4.3) at Jan 25, 2019 12:43 PM (UTC).
> 
> Homey software version: 2.0.0
> 
> Crash report:
> 
>     Note: this log has been manually submitted by a user.
> Log ID: 62aa2407-72d1-4062-af36-2f8bc0766f82
> 
> 
> 
> ---- stdout ----
> 
> 
> ---- stderr ----
> 
>     
>   
> N.B.: You will soon be able to view (an archive of) these logs from witin a developer panel on the app page.
