### ISSUE TITLE
Latest version v0.5.0 Xiaomi Zigbee shows strange temperature

### ISSUE THREAD

**Issue by jtebbens** [TedTolboom/com.xiaomi-mi-zigbee#125]
As of latest update my freezer jumps from -18c to -5c which is strange (closed door),
![image](https://user-images.githubusercontent.com/18558267/51896980-eb916700-23ad-11e9-92ff-ca2caba3f03e.png)

**Comment by volodeev** [comment]
I have the same display (
![image](https://user-images.githubusercontent.com/46497923/51899036-01b21e00-23d4-11e9-808c-95237d6248ee.png)
![image](https://user-images.githubusercontent.com/46497923/51902337-979d7700-23db-11e9-905d-19c3ed3142d9.png)

**Comment by rasssta** [comment]
![image](https://user-images.githubusercontent.com/4455235/51904066-02d85080-23be-11e9-9855-19974a24946c.png)

Same here. The peak at 23c is when I took the sensor out of the freezer for a while to see its behaviour out "in the wild".

**Comment by Dutchprop** [comment]
Same here:
![wine2](https://user-images.githubusercontent.com/42809610/51910274-07f1cb80-23cf-11e9-97d6-6e5cd6fe7033.PNG)

**Comment by TedTolboom** [comment]
Guys,

Likely the temperature reported by the lifeline report is incorrectly parsed.
Can you do me a favor since not all graphs are clearly readable?

Post the correct temperature and the incorrect temperature values. And verify what the interval is between the incorrect values.

Thanks, Ted

**Comment by Dutchprop** [comment]
Hi Ted, hopefully the below helps:
![wine3](https://user-images.githubusercontent.com/42809610/51914081-4b046c80-23d8-11e9-9a44-2dabadea6065.jpg)

**Comment by rasssta** [comment]
I've attached a CSV export from Homey Insights (rename to .csv). Everything warmer than -15 is inaccurate.

Ignore the values between: 2019-01-28   23:05:00	and  2019-01-29   00:35:00

[Xiaomi T_H - Freezer — Temperature (Last 24 Hours).txt](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/files/2808678/Xiaomi.T_H.-.Freezer.Temperature.Last.24.Hours.txt)

**Comment by TedTolboom** [comment]
Hmmm... looks like Athom did not (properly) solve this issue: https://github.com/athombv/homey/issues/2165#issuecomment-370257546

So the data is provided to the device driver is UTF-8 encoded...
I don't think it will be possible to correctly decode it again..

I'll check and other wise disable this reporting again (except for the battery reporting)

**Comment by Dutchprop** [comment]
It appears to be getting worse, the same 17,89 degrees is showing most of the time now:
<img width="1187" alt="schermafbeelding 2019-01-30 om 08 45 13" src="https://user-images.githubusercontent.com/42809610/51966021-a7649c00-246b-11e9-907a-fb823e599a66.png">

**Comment by volodeev** [comment]
@TedTolboom 
This is observed not only in reports. Changes are visible in the device and in tags!
![image](https://user-images.githubusercontent.com/46497923/51998307-37d9c580-24da-11e9-84e2-ed4e1d550ebc.png)

**Comment by TedTolboom** [comment]
@volodeev I would certainly hope so, otherwise more would need to be fixed.
The reports I'm mentioning are the device attribute reports; once received the device driver will update the capability, which then will update the value shown in the UI and trigger the corresponding triggercards.

I just disabled the temperature and humidity reporting from the lifeline reports in [version 0.5.1](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/releases/tag/v0.5.1)
Has been uploaded to the app store.

I'll close this issue for now. If not solved in v0.5.1, please comment and re-open.

**Comment by blex92** [comment]
hello,
i have a similar issue with aqara temperature and humidity sensor together with Xiaomi/Aqara Zigbee 0.6.1 software version on Homey running 2.5.2.
Every hour temperature goes up to around 7 degrees C on both sensors mounted in fridge (set to 5degC) and freezer (set to -18degC).
Is there any solution to fix it?

![aqara](https://user-images.githubusercontent.com/55997208/65903294-7e125c00-e3bc-11e9-8277-2d17ef4419ac.jpg)

**Comment by TedTolboom** [comment]
Will be re-fixed in v0.6.2 (awaiting Athom’s approval)

**Comment by blex92** [comment]
:) thanks for the quick reply :)
