### ISSUE TITLE
[Feature Request] Invert signal option for Aquara Door and Window Sensor

### ISSUE THREAD

**Issue by PeterEIER** [TedTolboom/com.xiaomi-mi-zigbee#127]
Add the option, in advanced settings, to invert the alarm signal like this:

**Not inverted**
open = alarm
closed = no alarm

**Inverted**
open = no alarm
closed = alarm

**Reasoning:**
I use these door/window sensors connected to a switch (which is normally open). If it would be possible to invert the signal my door/window sensor would not always show the alarm state but only when actually the button is pressed.

Thanks for taking into consideration.

**Comment by TedTolboom** [comment]
is this enhancement still actual?

**Comment by PeterEIER** [comment]
For me it is!

**Comment by rywr** [comment]
Hello Ted,
this request is important for me, too - I think also for other members in the Homey community.
I have several door sensors (used as rain sensor, door ring alert ...) where ist would be very useful to have the invert option. I asked for it in the community (Aqara thread) some times ago and I'm happy to see there are is already a feature request.
Bye
RonnyW @Homey community

**Comment by TedTolboom** [comment]
Added to 0.8.0

**Comment by koktaildotcom** [comment]
That's nice!
