### ISSUE TITLE
Links on Homey apps page not working

### ISSUE THREAD

**Issue by glennhmjoat** [TedTolboom/com.xiaomi-mi-zigbee#128]
Some of the product links on the Athom app website dont work

anything with xiaomi-mi.com fail to load

and this link fails too
https://apps.athom.com/app/com.xiaomi-mi-zigbee
current working link is https://apps.athom.com/app/com.xiaomi-mi

the Aqara links all seem fine

![image](https://user-images.githubusercontent.com/45816076/52144974-a37f8680-26c4-11e9-8202-838af1bfc95f.png)

**Comment by TedTolboom** [comment]
Thanks for reporting; will be corrected in v0.5.3
