### ISSUE TITLE
Some devices stopped connecting after update to version 2.0

### ISSUE THREAD

**Issue by bulubash** [TedTolboom/com.xiaomi-mi-zigbee#129]
After the update to version 2.0, the following devices stopped connecting:
-Aqara Smart Light Wall Switch (L) Single (QBKG04LM) - Before the update, the device was connected and worked fine
-Wireless switch WXKG01LM - previously connected devices work normally, new devices cannot be connected
-Aqara Wireless Remote Switch Single - WXKG02LM - device is connected but there are no settings inside, there is no possibility to set up commands

**Comment by bulubash** [comment]
Also, it will be good if next device will be supported - Aqara Water Leak Sensor User SJCGQ11LM
Thanks.

**Comment by TedTolboom** [comment]
Version 2 during introductions had some issues not releated to the app.
I will close this issue
