### ISSUE TITLE
Please add support for flood sensor 

### ISSUE THREAD

**Issue by bliekp** [TedTolboom/com.xiaomi-mi-zigbee#131]
Please add support for the flood sensor. 

€ 11,13  58％ Off | 2018 Newest Xiaomi Mijia Aqara Water Immersing Sensor Flood Water Leak Detector for Home Remote Alarm Security Soaking Sensor
https://s.click.aliexpress.com/e/cqmZYxIs

**Comment by chinswain** [comment]
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/26

**Comment by TedTolboom** [comment]
Duplicate of #26
