### ISSUE TITLE
Problem with Aqara Wireless Remote Switch Double WXKGO2LM

### ISSUE THREAD

**Issue by Bhitv** [TedTolboom/com.xiaomi-mi-zigbee#135]
Hello Ted
With the upgrade to version 2.0, two double zigbee switches from Xiaomi / Aqara WXKGO2LM were not included in the upgrade.
There is an exclamation mark and when I click them I get the message "unknown problem"
Now I want to delete them and then link them again with Homey.
However Homey sees the switches no longer, when I delete it, I get the message: "status.could_not_find_zigbee_shepherd_device"
When I pair them again, I get the message that the switch already exists.
I have connected a new switch of the same type, this works fine.
But I would like to use the old switches again, do you have a solution to delete them?.

Translated with Google translation, I prefer a Dutch answer.

Thank you for the effort
Kind regards Bas Huisintveld

**Comment by Moskvitch** [comment]
HI, same problem here. One of the Double WIreless Rocker switches got the dreaded red triangle with an exclamation mark.

After upgrading to v2 a while ago I had to reinstall the app to get rid of old Aqara Zigbee stuff and pair it again, because I could not delete the, individually.

Then everything had been working fine and then yesterday, one (not all) of the switches became unresponsive.  When pressed. I get

**Device is unavailable

Device has left the network, please remove and re-pair**

and then, like right after upgrading to v 2.0, if I try to do as instructed, I get

**status.could_not_find_zigbee.shpeherd_device**

Its like you can only remove devices that are on-line, but can't remove dead ones.

Please help, as it would be a major pain to go nuclear again and reinstall the app reading more than 10 devices, recreating apps, etc.
Much appreciated!

**Comment by Moskvitch** [comment]
And now I tried to add the switch again but after a couple of minutes of "interviewing clusters", etc I got the **duplicate device** error :( :( :(

**Comment by Bhitv** [comment]
We do not get an answer to this problem, probably not important enough.
I have already mentioned 2 other problems after transferring.
You will receive a notification that it is being forwarded to the technical department, and after that you will not hear anything.
I am still having major problems.

**Comment by Moskvitch** [comment]
Yeah, but this Zigbee app is not developed by Athom, but by a private individual working in his free  time on pure inspiration and maybe some donations.

Athom should really create an App Store with paid apps so we could expect stuff after paying for it.  And in our particular case, given the growing demand for integrating cheap and quality-made Xiaomi smartphone devices, Athom should just make him Ted Tolboom a generous offer before the Xiaomi behemoth makes everything compatible with its own hub instead, rendering our beloved Athom Homey (no irony here, I really like our little "kolobok") completely obsolete.

Did you know that, in addition to the well-advertised collaboration between Xiaomi and IKEA, there's a "lab feature" in the Mi Home app hinting at integrating about 15 smartphone manufacturers' products?  It does not work yet, but is a sign of things to come.  And the list is growing with each update...

**Comment by Bhitv** [comment]
Yes all well and good, but for the version change all Zigbee devices worked fine, after that half of the devices no longer work, and can not be reinstalled, because Homey says they are already present.
They can not be wiped out, worthless.
Ted is the contact person for this app.
So I can expect an answer at least after 7 days of waiting, even if he does not know the solution.

**Comment by Moskvitch** [comment]
I understand - and as you can see above - share your frustration.  But Ted is the guy that wrote this plugin (they very confusingly keep calling these "apps"), not the contact person for Athom B.V.  Just a guy that does coding.  That's the flip side of buying a EUR299 device from a company that evolved from a kickstarter project vs a major smarthome device manufacturer.  But!  In all honesty, I like this better.  Try contacting Aqara with some problem - the only way to contact is to send an email to God knows who and then maybe you get a response from "Jasmine" :)  that you can barely understand :)  In this case there is a real human being that may take some time to respond.
I recently contacted PAYPAL (!!!) with an issue that was really their problem and all I got is a bunch of apologetic emails from several people that didn't;t even bother to read my initial letter (and offered no solution, either).
So, yes, this is frustrating, but at least there's a face to this "problem" :)

**Comment by Bhitv** [comment]
I know, Ted Tolboom is a good guy, I've had contact with him with problems before.
But it is my wife who keeps on acid when the light does not work again, or when she can not read the outside temperature anymore.

But I have installed a few new switches, only the old ones remain in Homey.

We are waiting, that is the only thing you can do now

**Comment by Moskvitch** [comment]
Just tell her "Honey, they say if there's a problem with a _home device_, I should _remove_ it and _re-pair_.  What do you think of that approach?" :):):)

Sorry, just couldn't help it :):):) 

PS Plus, as we know, it's all a big lie, you can't actually remove it :):):)

This is going waaaaaay off-topic and borderline offensive, so my apologies ! :)

**Comment by Moskvitch** [comment]
Ha! It worked.  Just tried again.  First I got a new screen 

Removing device...
If the device is not removed automatically try enabling its 'pair' mode.

After a while I got another screen:

status.remove_device_timeout

If you want to remove the device even though it could not be found, click the button 'Remove'.

Note: this might require you to reset the device before it can be added with Homey again.

And, lo and behold upon pressing (not clicking :) ) the Remove button it was gone!

So, just try again?

**Comment by Bhitv** [comment]
Thanks, I will try it

**Comment by Bhitv** [comment]
Yes, I finally succeeded.
But had to link it first, got the error message "Is already present".
Then I could remove it manually.
Now I have to solve the rest of the zigbee problems.
Long live the upgrade to version 2.0

Thanks for the tip

**Comment by Moskvitch** [comment]
Now my other Wireless Double Rocker died on me.  Same exact symptoms as above.  Now we know how to re-add now, and it’snice that they are taking turns and not dying all at once, but perhaps there’s something to look into?  I have three, and this is number two.
