### ISSUE TITLE
Xiaomi bedside lamp support

### ISSUE THREAD

**Issue by Kronan** [TedTolboom/com.xiaomi-mi-zigbee#136]
Really would like to see support for the xiaomi bedside lamp ,<3

**Comment by TedTolboom** [comment]
Hi @Kronan,
I think the bedside lamp is already supported by the Xiaomi Mi Home app: https://apps.athom.com/app/com.xiaomi-miio

My app is only focusing on the Zigbee based Xiaomi / Aqara devices. So from that perspective I will not add support for this device to my app.
