### ISSUE TITLE
Timeout adding a device

### ISSUE THREAD

**Issue by stefanprotzman** [TedTolboom/com.xiaomi-mi-zigbee#138]
Since the update to homey 2.0.4. and Xiaomi mi home zigbee app to 0.5.4. im not able tot add a human body sensor. I've tried different ways, but nothing will help. I released the button on the sensor on many ways after different times, pressed IT after every 2 seconds.

Are there more people having the same issue?

Whats the solution?

**Comment by yan-zaitsev** [comment]
@stefanprotzman did you solve your problem? I have same problem :(
