### ISSUE TITLE
Vibration sensor

### ISSUE THREAD

**Issue by Roppieee** [TedTolboom/com.xiaomi-mi-zigbee#139]
Hi, i have 2 vibration sendors and they are not reporting the fibration level. It seems like the values are not updated (only sometimes).Even when i manually create a fibration alarm, there is no change in the vibrationlevel reading. Im on 2.0.5 rc 5 and the latest xiaomi app

**Comment by rvmuilekom69** [comment]
Same here, on version 2.05

**Comment by chinswain** [comment]
Same issue for me, I have an existing vibration sensor that was added some time ago (functions perfectly). I cannot add a second device. (The sensor is not detected at all during the add device process).
