### ISSUE TITLE
Zigbee qara temperatuur and humanity 

### ISSUE THREAD

**Issue by ronald2404** [TedTolboom/com.xiaomi-mi-zigbee#142]
Hi since homey 2.0.5 the value of temperature and humidity is not updated. All 8days old. Also I wonder if you can set update frequence and what default preset is?

**Comment by ronald2404** [comment]
9397023f-035a-458f-8ec7-31cde6910295

**Comment by JustThe2ofUs** [comment]
Same issue here. Updating interval differs from device to device. 🤷‍♂️

**Comment by JustThe2ofUs** [comment]
Push* 
The devices are literally not working

**Comment by JustThe2ofUs** [comment]
Maybe this App is deadish...
