### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by PetrichorXyz** [TedTolboom/com.xiaomi-mi-zigbee#146]
**Homey:** v2.0.5
**App:** v0.5.4 - 04.03.19
**Gebruikte hardware:** Aqara Vibration Sensor 

Bij starten van de App crashed hij.

![afbeelding](https://user-images.githubusercontent.com/2332343/55000465-d9f5c580-4fd2-11e9-9380-815eb811565d.png)

**Comment by stefanprotzman** [comment]
Helaas wordt er nergens op gereageerd en lijkt er geen oplossing te komen. De top aqara sensoren zijn compleet nutteloos geworden zonder ondersteuning van de ontwikkelaar of athom.

**Comment by PetrichorXyz** [comment]
@stefanprotzman: De Xiaomi / Aqara ZigBee app is een zogenaamde communityapp en is dus niet van Athom. Een door een vrijwilliger gemaakte app. Ik snap dat de ontwikkelaar er ook wel eens een week geen tijd voor heeft ondersteuning te bieden.

@TedTolboom :
Na upgrade naar v2.1.0-rc.2 is bij het probleem verholpen.
