### ISSUE TITLE
Homey Update 2.1.1 Timeout does not add new sensor Zigbee to Xiaomi Zigbee App

### ISSUE THREAD

**Issue by RossBrisbane** [TedTolboom/com.xiaomi-mi-zigbee#147]
I cannot add/have trouble with Xiaomi Sensors directly through Zigbee in Homey 

Adding a sensor switch button round (Mi) Zigbee based fails to add but responds initial reset. It just does time out. Following all instruction including resetting in adding device procedure. Just timeouts.

**Comment by Lavve** [comment]
Same issue with my xiaomi/aqara devices. I have today 12 zigbee units connected to Homey witch was added before the 2.0 update. After the update I cannot add zigbee devices anymore.
