### ISSUE TITLE
Xiaomi/Aqara app crashes

### ISSUE THREAD

**Issue by deadoolish** [TedTolboom/com.xiaomi-mi-zigbee#149]
Since yesterdayish the app starting to crash, after rester it crashes again within 10-15 hours. I did reinstall Trådfri app yesterday due to tried to add some more lamps but didnt worka and disabled it again, dont know if this triggered the crashes... 
App version 0.5.5, Homey 2.1.1
Report:1b039b32-7d8e-4546-b0d0-fda823ebd6e6

**Comment by TedTolboom** [comment]
@deadoolish the report provided is a manually created report, not showing any data.
I'll close this issue for now, it it reoccurs, please reopen
