### ISSUE TITLE
Temperature/humidity sensors won't pair

### ISSUE THREAD

**Issue by mikevbruggen** [TedTolboom/com.xiaomi-mi-zigbee#150]
Just purchased 2 Xiaomi/aqara temperature/humidity sensors.
both wont pair with the homey app. They both blink 3 times as required by the app but after that nothing happens.

I tried reinstalling the app and restarting homey but no succes.
It keeps onlys showing the install instructions screen and after that the time out screen.

Homey Pro (early 2019)
Homey version 2.1.1
App version 2.2.1.299
node.js versie v8.12.0

Mi zigbee app v0.5.5

edit:
I also tried the Door and window sensors, they have the same issue.
Also tried the sensors on a older Homey (early 2016) from my father, here all the sensors pair without any problems. All the software versions (homey and the mi zigbee app) are exactly the same as on my homey pro.

**Comment by HansBouwman** [comment]
Hi,

Same issue here with every aqara device I try. It worked in the beginning but after 2 days the temp. sensors lost connection. I removed all devices. app and resented the zigbee network. After that the only Aqara devices that work are the motion detector and the wireless switch (2018). The door/window sensors and temp. sensor will not pair.

**Comment by mikevbruggen** [comment]
> Hi,
> 
> Same issue here with every aqara device I try. It worked in the beginning but after 2 days the temp. sensors lost connection. I removed all devices. app and resented the zigbee network. After that the only Aqara devices that work are the motion detector and the wireless switch (2018). The door/window sensors and temp. sensor will not pair.

hi, thanks for your reply, Any updates on getting it to work? and do you have a homey pro or the "normal" version?

**Comment by HansBouwman** [comment]
Yes finally got it to work one by one. The Aqara stuff is very sensitive if you press the "learn mode" button too quick it will not work. If you first select the right device in Homey add device screen, wait for the screen that says tot put the device in learn mode and then press the device button for 3 seconds most of the times it works. Sometimes you have to be very patient for it to work. In my experience the z-wave stuff works much better but you pay a higher price for that. btw I have a Pro Version of Homey.

**Comment by mikevbruggen** [comment]
Hello Hans,

Happy for you that you got it working again, unfortunately i still cant pair the Aqara devices with my homey pro (tried everything i described, and only start pressing when the screen asks me to). still hoping Ted has an idea what the issue can be. i also contacted Homey support for this issue but the directed me back to the App developer for help.

**Comment by TedTolboom** [comment]
@mikevbruggen let’s see if we can solve the problem.

Can you check if the Zigbee chip is correctly booted by going to  https://developer.athom.com/tools/zigbee and check if this page is loading correctly or showing an error?

Can you share a sceenshot of the nodes overview? Do you have any other Zigbee devices added to the Homey pro?

Which device are you actually using? The round Xiaomi temperature sensor with a pinhole button or the square Aqara temperature sensor with a normal button?

In both cases, you might want to try to include them by following the inclusion instructions (at close proximity of Homey) and then keep pressing the button on a 1-2 second interval until the inclusion is successful.

**Comment by mikevbruggen** [comment]
Hello ted,

Thank you for your reply!
here we go:
![image](https://user-images.githubusercontent.com/50182320/57650586-70099d80-75cb-11e9-89fe-7cbbea4bae9d.png)

![image](https://user-images.githubusercontent.com/50182320/57650646-8fa0c600-75cb-11e9-9d42-ff0e56787712.png)

as you can see i have a lot of IKEA Tradfi led bulbs. what i do notice now for the first time is that some bulbs are shown more then once in the list? is this common? they dont show up multiple times in my devices list on the homey app.

The device i am using (and tested OK on a normal homey) is the square aqara temperature sensor.

I tried your last suggestion about the inclusion instructions at close range (even tried with holding the sensor on top of the homey) and keeping the sensor alive after pressing it for 5 seconds to make the LED blink 3 times multiple times already, but sadly without succes.

If you need more info or have some suggestions i could try let me know!

Thanks again for helping so far!
