### ISSUE TITLE
Aqara vibration sensor sensitivity

### ISSUE THREAD

**Issue by piveslat** [TedTolboom/com.xiaomi-mi-zigbee#151]
According to the specs of the sensor, it should be possible to set sensitivity level for vibrations between 1-23 where 1 is most sensitive to trigger an alarm. This value is not possible to set in the app, an improvement possibility?

**Comment by TedTolboom** [comment]
In the current version of the Zigbee core, it is not possible to change this setting.
We'll need to wait until Athom has released the rewrite and provides this option.

Since no timing is mentioned by Athom, I will close this issue for now.
