### ISSUE TITLE
Add support for Aqara Wireless Relay Controller

### ISSUE THREAD

**Issue by PeetersJan** [TedTolboom/com.xiaomi-mi-zigbee#152]
Add support for:
https://xiaomi-mi.com/sockets-and-sensors/Wireless Relay Controller/

![4c759c87-2de5-4c00-aeec-c13c67e51f15](https://user-images.githubusercontent.com/39444710/57979747-5a103880-7a22-11e9-8d4f-439558b9b516.jpg)

reference info:
Brand | Aqara
Model | LLKZMK11LM
Zigbee Model | lumi.relay.c2acn01
Wireless Connections | Zigbee

Probably, **adding the device to the wall switch driver will suffice**. 
When added as a (double) wall switch, it will be added as a generic device and thus not work correctly.
See: https://github.com/guyeeba/Hubitat/blob/master/Drivers/Aqara%20QBKG11LM-QBKG12LM-LLKZMK11LM.groovy
_____________________________________________________________________________________________________
"Documentation" |  https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1411
_____________________________________________________________________________________________________
A driver, based upon the wall switch driver  |  https://github.com/guyeeba/Hubitat/blob/master/Drivers/Aqara%20QBKG11LM-QBKG12LM-LLKZMK11LM.groovy

// two buttons, neutral required (QBKG12LM)
// reports:
// - endpoint 0x01, cluster 0x0006 (on/off),           attr 0x0000: Left button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
// - endpoint 0x05, cluster 0x0012 (multistate input), attr 0x0055: Left button pushed (value = 0x0001)
// - endpoint 0x02, cluster 0x0002 (on/off),           attr 0x0000: Right button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
// - endpoint 0x06, cluster 0x0012 (multistate input), attr 0x0055: Right button pushed (value = 0x0001)
// features:
// - Disconnect left button from relay: write uint8 (0x20) value (connected: 0x12, disconnected: 0xFE) to attribute 0xFF22 of endpoint 0x01, cluster 0x0000
// - Disconnect right button from relay: write uint8 (0x20) value (connected: 0x22, disconnected: 0xFE) to attribute 0xFF23 of endpoint 0x01, cluster 0x0000
____________________________________________________________________________________________________
Log file  |  https://github.com/dresden-elektronik/deconz-rest-plugin/files/3106838/xiaomi_relay.zip
_____________________________________________________________________________________________________
LLKZMK11LM
switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l1 }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/l1/set"

switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state_l2 }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/l2/set"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
___________________________________________________________________________________________________
metadata {
    definition (name: "Aqara Wall Switch (QBKG11LM, QBKG12LM, neutral), Double relay (LLZKMK11LM)", namespace: "guyee", author: "Péter Gulyás") {
        capability "Configuration"
        capability "Refresh"
		capability "PushableButton"
		capability "DoubleTapableButton" // QBKG12LM only
		capability "Power Meter"
		capability "Energy Meter"
		capability "Temperature Measurement"

        command "childOn"
        command "childOff"
        command "childRefresh"
        command "recreateChildDevices"
        command "deleteChildren"
		// two buttons, neutral required (QBKG12LM)
		// reports:
		// - endpoint 0x01, cluster 0x0006 (on/off),           attr 0x0000: Left button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
		// - endpoint 0x05, cluster 0x0012 (multistate input), attr 0x0055: Left button pushed (value = 0x0001)
		// - endpoint 0x02, cluster 0x0002 (on/off),           attr 0x0000: Right button relay state (first octet 0x00=off, 0x01=on, the rest is Xiaomi-specific stuff)
_____________________________________________________________________________________________________

![2019-05-19 10 33 08](https://user-images.githubusercontent.com/39444710/57979718-0dc4f880-7a22-11e9-973f-5a6666c99dea.jpg)
![2019-05-19 10 32 59](https://user-images.githubusercontent.com/39444710/57979719-0dc4f880-7a22-11e9-9323-0c414449d3a1.jpg)

**Comment by Atomicprogress** [comment]
Hi, 
will it be compatible? 
if yes when?

**Comment by PeetersJan** [comment]
Don't know, it is awfully quiet here...  🤔

**Comment by TedTolboom** [comment]
@PeetersJan see my PM I send you on the community forum.

Yes, I can integrate this device into the app, but experience with both Aqara and Homey’s Zigbee implementation is that I need to have the device myself to implement, debug and be able to support the follow-up questions. 

So I would need to order a device first before I can implement support for it.

You can contribute by a paypal contribution to enable ordering.

**Comment by PeetersJan** [comment]
Perfect! I will make a paypay donation!

**Comment by PeetersJan** [comment]
... but how :-)
Could you maybe point me to the right spot?
Thanx!

**Comment by Atomicprogress** [comment]
Great! I will also make a donation! could you write the link for the paypal donation?

**Comment by TedTolboom** [comment]
@PeetersJan thanks!
@Atomicprogress see the link at: https://apps.athom.com/app/com.xiaomi-mi

Much appreciated both!

**Comment by Atomicprogress** [comment]
donation made, keep us updated :-)

**Comment by Atomicprogress** [comment]
Hi Ted,
there are news?

**Comment by Atomicprogress** [comment]
Hi Ted,
could you give us an answer?
Did you buy the Aqara Wireless Relay Controller with our donations?
You are working to add in your application?

Tnx

**Comment by TedTolboom** [comment]
@Atomicprogress yes I started working on the implementation, but failed to finish it (in a testable form) before my summer holidays. 
I will continue / finalize mid of August.

**Comment by Atomicprogress** [comment]
@TedTolboom Perfect, we look forward!! thanks :-)

**Comment by phgmhendrix** [comment]
@Atomicprogress as an appreciation I have sent a donation also!
Hopefully we can expect support for this device soon.

Maybe a bit off-topic but: do these devices fit in the wall behind a standard pulse-switch?

**Comment by GPBruins** [comment]
@TedTolboom When can we expect the relay to be included?

**Comment by TedTolboom** [comment]
Sorry guys... finally found some to work on it...
But the relay device I have appears to be dead.

Will need to start ordering one from China.

**Comment by TedTolboom** [comment]
v0.6.0 with support for the Aqara relay is awaiting App store approval by Athom.

@PeetersJan @GPBruins thanks for supporting this activity.

I will close this issue, since completed
