### ISSUE TITLE
Aqara Yeelicht dimmer

### ISSUE THREAD

**Issue by shideban** [TedTolboom/com.xiaomi-mi-zigbee#155]
Is it possible to incluud this Aqara Yeelight dimmer

**Comment by chinswain** [comment]
This is a bluetooth device so would not be included in this library.

**Comment by shideban** [comment]
Beste.

Bedankt om dit na te kijken. Ik had er geen idee van dat dit werkte via
bluetooth.
Zo zie ja maar, ik leer elke dag bij.
Jammer, maar niet getreurd, komt nog welwel vannaar pas.

Mvg
Serry Wendy

Op ma 15 jul. 2019 12:34 schreef chinswain <notifications@github.com>:

**Comment by TedTolboom** [comment]
Question answered
