### ISSUE TITLE
Motion sensor not reporting illuminance

### ISSUE THREAD

**Issue by matpit** [TedTolboom/com.xiaomi-mi-zigbee#156]
Hello,
It seems like the motion sensor only reports illuminance when the motion alarm is triggered.
Is it possible to get updates from the luminance-detector even though no motion is detected?
Right now the last report is 14 hours ago, the luminance must have changed during the night :)

**Comment by JustThe2ofUs** [comment]
Hey; you’re right, this is how it works. 
afaik it’s not possible but probably someone knows a workaround / flow to pretend motion is triggered.

**Comment by matpit** [comment]
Do I have to buy a zigbee spider that climbs over the motion sensor every 15 minutes?
Or is there an easier way?

**Comment by TedTolboom** [comment]
Yes, could be an option.
No, not that I and developers on other home automation networks am aware of.

Like mentioned, this is a known device limitation that can’t be changed.

I’ll assume that this answers your question (perhaps not the desired answer) and close this issue as such
