### ISSUE TITLE
Xiaomu single wall switch (L)

### ISSUE THREAD

**Issue by shideban** [TedTolboom/com.xiaomi-mi-zigbee#157]
Best.  

I would like to raise the following problem.  I am replacing all switches in the home with switches from Xiaomi.  However, with the last purchased copies I can't get it connected to the Zigbee network via the Homey app.  I get an error message every time.  The LED lights continue to flash red.  I could understand that one copy is defective, but I think four copies are at least bizarre.  Since the specifications state that it is a model 2019, I therefore rather think that it is a software problem.  Maybe the app needs an update.  I would like to know your opinion on this.  Sincerely.  

PS, the app works differently with the other xiaomi products excellent.

**Comment by TedTolboom** [comment]
@shideban what is the exact error message shown and what is the exact product number?
Is it added as Basic Zigbee device to Homey? If so, can you post the ID's of the device as shown in settings?
