### ISSUE TITLE
Aqara motion sensor hacked - needs a little change in the driver

### ISSUE THREAD

**Issue by Piotr-Grochowski** [TedTolboom/com.xiaomi-mi-zigbee#158]
Aqara motion sensor can be easily hacked to report motion every 5s instead of 60s which makes it much more usable. It works perfectly and doesn't have much impact on battery (checked it myself!). Here is how to do it: https://community.smartthings.com/t/making-xiaomi-motion-sensor-a-super-motion-sensor/139806

Unfortunatelly in Homey driver there is a limitation for min motion alarm reset to 60s. It will be much appreciated to change this parameter to 5s instead of 60s. 

It's in app.json:
{
          "id": "alarm_motion_reset_window",
          "type": "number",
          "label": {
            "en": "Disable motion alarm after",
            "nl": "Schakel bewegingsalarm uit na"
          },
          "hint": {
            "en": "This setting will disable the motion alarm after the given time (in seconds) has expired. Every time motion is observed by the device it will reset this timeout.\nRange: 60 - 86400, default: 300 [s]",
            "nl": "Deze instelling zal het bewegingsalarm uitschakelen na de tijd (in seconden) is verstreken. Elke keer dat opnieuw beweging wordt gedetecteerd wordt deze timer herstart.\nBereik: 60 - 86400, Standaard: 300 [s]"
          },
          "value": 300,
          "attr": {
            "min": 60,
            "max": 86400
          }

Parameter "min" should be changed to 5s to allow users to properly use hacked sensors. 
Is it possible to change it in the app?

**Comment by TedTolboom** [comment]
Yes and no.
No, by default behaivior the minimum reset window is 60 seconds. So I won't change the default number considering thousends of users might start asking why the sensor doesn't respond that fast.

But, yes, I've added an expert setting overriding the minimum time in v0.6.0 of the app update (pending approval)

**Comment by Piotr-Grochowski** [comment]
Expert option is a great thing, but it will be better to make it a number value, not the checkbox (so user can change it to e.g. 10 or 15s, etc. - depending on the needs).

**Comment by TedTolboom** [comment]
I don't see an option to implement, based on current Homey settings UI, in such a way that it is not creating too many questions with the majority of the user base. If I lower the minimum value for all, people will start complaining that the app is broken / the sensor is not reporting within the 60 seconds hard-coded into the device.

IMHO the hack will only be implemented by a minority. In that case, the implemented expert option is providing the right solution.

**Comment by Piotr-Grochowski** [comment]
I think you misunderstood me. You are right about majority of users that will use standard, non-hacked sensor. So the standard option should remain as it is, with minimum 60s. But the expert should be done a bit different, because in current form it will make the flows harder to implement (or even unable to do properly). In the hardware after soldering the sensor stays inactive for 5s and after that time it starts to work again. If the driver will have hardcoded 5s value (as it is now in 0.6.0 after activating expert mode), then in Homey the driver will set sometimes "no motion" before the sensor start to work again, so the sensor in Homey will behave sometimes like this (if the motion is continuous whole the time):
1. Motion detected
2. No motion detected (after 5s)
3. Motion detected (after a few milliseconds)
...

So there are no-motion events for a few miliseconds instead of continuous "motion detected" until there is no real motion.

So in practice I don't set it to 5s, but to 6-7s (if I need fast response, because for some scenarios I set e.g. 30s - depending on demand, it makes some flows easier to implement if it's set on driver side, not a timeout in the flow). Of course I do it in my copy of your driver with my modifications.

So in summary - it would be great to allow to input exact value, that the delay should be overwritten with. Then maybe instead of checkbox make a dropdown with default value NO for non-hacked sensor and delay values between 5s and 60s. If it's set to NO, then it works like a standard sensor, if it's set to some value, then it overrides delay with this value. The setting could be done like this:

             {
                "id": "hacked_alarm_motion_reset_window",
                "type": "dropdown",
                "label": {
				  	"en": "Hacked sensor"
				  },
					"hint": {
						"en": "By soldering two contact points on the PCB it's possible to reduce the motion blind time to 5 seconds instead of the minimum 60 seconds. Enabling this setting will allow you to override the minimum of 60 seconds for cancelling the alarm and will set it to 5 seconds.",
				    "nl": "Door twee contactpunten op de printplaat te solderen is het mogelijk om de blindtijd van de sensor terug te brengen naar 5 seconden. Inschakelen van deze instelling maakt het mogelijk om de instelling voor het annuleren van de bewegingsmelder te overschrijven tot 5 seconden."
		},
                "value": "off",
                "values": [
                  {
                    "id": "off",
                    "label": {
                      "en": "OFF"
                    }
                  },
                  {
                    "id": "5",
                    "label": {
                      "en": "5 sec"
                    }
                  },
                  {
                    "id": "6",
                    "label": {
                      "en": "6 sec"
                    }
                  },
... and so on....

What do you think about such a solution?
