### ISSUE TITLE
Will not add anymore devices

### ISSUE THREAD

**Issue by homedean** [TedTolboom/com.xiaomi-mi-zigbee#161]
I have multiple motion, temperature, door sensors and buttons, all working well and effectively.

However now the homey is refusing to add any more devices.  Tried a temp, door, button and motion sensor.  A couple of units new out of box, a couple older units that I haven't used in a while.

Any help would be hugely appreciated!

0cbf5eb2-7b1e-4ddf-ac74-5e59f899baf4

**Comment by rgerr** [comment]
Have you rebooted your device? And checked if the memory is not full?

**Comment by TedTolboom** [comment]
@homedean do you have any routing devices (mains powered) installed on the Zigbee network?
Homey simply refuses to add more battery powered sensors if routers are not present. If I recollect correctly, 1 router : 15 battery devices
