### ISSUE TITLE
Add support for the XIAOMI Mijia camera

### ISSUE THREAD

**Issue by mackelito** [TedTolboom/com.xiaomi-mi-zigbee#163]
This one :) https://www.banggood.com/Battery-Version-XIAOMI-Mijia-CMSXJ11A-1080P-Smart-Wireless-APP-Control-IP-Camera-Waterproof-Outdoor-Camera-AI-Moving-Detection-Infrared-Nighte-Version-Baby-Monitors-p-1498519.html

**Comment by TedTolboom** [comment]
This camera is not Zigbee based, and therefore falls outside the scope of this app.

**Comment by mackelito** [comment]
Damn.. sorry for missing that!
