### ISSUE TITLE
Add support for Aqara Water sensor :-)

### ISSUE THREAD

**Issue by Svegg** [TedTolboom/com.xiaomi-mi-zigbee#164]

**Comment by rgerr** [comment]
+1

**Comment by rgerr** [comment]
Devices Work in Progress (awaiting additional clusters in Homey's Zigbee implementation)

MiJia Honeywell Smoke Detector White
MiJia Honeywell Gas Leak Detector
MiJia Aqara Water sensor

**Comment by TedTolboom** [comment]
Thanks @rgerr for reading the readme; still needs to be resolved by Athom
