### ISSUE TITLE
Is the gateway necessary to use supported Aqara smart devices with homey?

### ISSUE THREAD

**Issue by ashleywolf87** [TedTolboom/com.xiaomi-mi-zigbee#167]
Is the gateway necessary to use supported Aqara smart devices with homey?

**Comment by rgerr** [comment]
No, you can add them to Homey without the Xiaomi gateway. Please note that in order to have a solid Zigbee network, you need powered Zigbee devices. Devices that work on battery do not empower the Zigbee network, but devices like lightbulbs do (when powered).

**Comment by ashleywolf87** [comment]
What if I wanted to use Aqara Door/Window sensors to automate flows around the house? Those run on batteries

**Comment by rgerr** [comment]
Depending on the size of your home, you would have to use Zigbee repeaters. For example Hue lightbulbs or Osram sockets. Add those to your Zigbee network on Homey and it will function as a mesh network which will enhance the signal for your Xiaomi contactsensors. From experience I can tell you this works like a charm.

**Comment by ashleywolf87** [comment]
does any device that uses zigbee function as a zigbee repeater or do i specifically need a repeater for zigbee? My home is an apartment(single floor) with 1590sqft of floor space

**Comment by rgerr** [comment]
You can ofcourse try without any powered devices, only powered (as in connected to the main power line) are being used as repeaters, such as Zogbee lightbulbs and outlets. Are you planning to use smart lightbulbs? If so, choose lightbulbs that use ZigBee and connect them to Homey. That will improve your ZigBee network in case Homeys ZigBee network is not sufficient.

**Comment by ashleywolf87** [comment]
unfortunately my setup doesnt use any smart bulbs. All might lights will depend on Sonoff T3 smart switches flashed with tasmota to work with Homey. 

So meaning to say as long as the smart device has zigbee functionality and it is a device which is powered NOT via a battery, it immediately functions as a mesh router?

**Comment by rgerr** [comment]
Exactly.

**Comment by TedTolboom** [comment]
@ashleywolf87 I guess your original question has already been answered by @rgerr (thanks for that). I'll close this issue for now.
