### ISSUE TITLE
Add support for the Aqara Camera G2

### ISSUE THREAD

**Issue by fschaal** [TedTolboom/com.xiaomi-mi-zigbee#169]
This one: https://nl.aliexpress.com/item/32843546982.html?spm=a2g0o.productlist.0.0.2d957ca0BlG5ny&algo_pvid=b056af2d-1cdd-4e92-a97f-3e659db9d784&algo_expid=b056af2d-1cdd-4e92-a97f-3e659db9d784-1&btsid=752e97f6-e4a1-4097-b94a-b3dbd9f48800&ws_ab_test=searchweb0_0,searchweb201602_3,searchweb201603_52

**Comment by TedTolboom** [comment]
Aqara Camera G2 is not a Zigbee based device, but a seperate controller that will not be supported by this app
