### ISSUE TITLE
Adding air pressure offset

### ISSUE THREAD

**Issue by Dgh1974** [TedTolboom/com.xiaomi-mi-zigbee#170]
Hi 

Can the air pressure get an offset setting ?
Its a few mbar off.

**Comment by TedTolboom** [comment]
@Dgh1974 this might be possible, but this change will not be high on the prio list to add.

**Comment by TedTolboom** [comment]
Next update

**Comment by Dgh1974** [comment]
Toppie .. thanks 👍

Verstuurd vanaf mijn iPhone X

Op 26 feb. 2020 om 20:29 heeft Ted Tolboom <notifications@github.com> het volgende geschreven:

﻿

Next update
