### ISSUE TITLE
No logging in a timeline available for Vibration sensor

### ISSUE THREAD

**Issue by mjolink** [TedTolboom/com.xiaomi-mi-zigbee#171]
For several devices (e.g. motion sensor) the history is saved in a timeline. The vibration sensor also shows this option, but the statement is "er is nog geen apparaat historie".  When I tap the sensor the vibration alarm is turned on, so there is contact between the device and Homey.

Using:
App version V0.5.5
Homey V2.5.2

**Comment by JustThe2ofUs** [comment]
While I am in love and in hate at the same time w/ my Homey and the Xiaomi-App I still am very eager to help where it’s possible. 😉😄 Suggestion:

Did you install the App Heimdall?
If not: Do so. Go to the Apps settings and enable “log” for your vibration sensors.
Then do something with them and check the history timeline IN THE HEIMDALL APP if the device reacted to your actions (can be seen in realtime).

-- // via mobile //
Am 3. Sept. 2019, 4:55 PM +0200 schrieb mjolink <notifications@github.com>:

**Comment by mjolink** [comment]
Thnx for your quick reaction!
I have Heimdall installed and have tested your suggested scenario. In the Heimdall app the vibration detection is registered in the timeline of the app. It is not logged in the device timeline under Devices.

**Comment by JustThe2ofUs** [comment]
Timeline in the device doesn’t track the events of the device. Pretty sure that it is not made for that?!

You may want to try the following workaround:
Create a flow. Under „THEN“ choose Heimdall, send value to timeline and as a Tag select the values of the vib sensor you want to see.
At least you will see something in the general timeline then.


-- // via mobile //
Am 3. Sept. 2019, 9:58 PM +0200 schrieb mjolink <notifications@github.com>:

**Comment by TedTolboom** [comment]
@mjolink by default Athom chose not to start logging all sensor data in the devices timeline.
What would be the added value to see all this data?

**Comment by mjolink** [comment]
I can't remember adjusting a setting where I turned on logging of e.g. motion for Aqara devices. I do like the option of seeing in 'apparaten' of a specific sensor when it was triggered. Currently it works for all sensors, but not for the vibration sensor.

**Comment by TedTolboom** [comment]
I'll check what is needed to add it to the timeline. Should be a large action

**Comment by mjolink** [comment]
thnx!

________________________________
Van: Ted Tolboom <notifications@github.com>
Verzonden: dinsdag 17 september 2019 09:51
Aan: TedTolboom/com.xiaomi-mi-zigbee <com.xiaomi-mi-zigbee@noreply.github.com>
CC: mjolink <mjolink@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [TedTolboom/com.xiaomi-mi-zigbee] No logging in a timeline available for Vibration sensor (#171)


I'll check what is needed to add it to the timeline. Should be a large action

**Comment by TedTolboom** [comment]
sssst... while awaiting the approval of 0.6.0, I added another present...

**Comment by mjolink** [comment]
Great Ted, thnx a lot for your service!!
Keep up the good work!

________________________________
Van: Ted Tolboom <notifications@github.com>
Verzonden: dinsdag 17 september 2019 21:49
Aan: TedTolboom/com.xiaomi-mi-zigbee <com.xiaomi-mi-zigbee@noreply.github.com>
CC: mjolink <mjolink@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [TedTolboom/com.xiaomi-mi-zigbee] No logging in a timeline available for Vibration sensor (#171)


sssst... while awaiting the approval of 0.6.0, I added another present...
