### ISSUE TITLE
Aqara Wireless Remote Switch (2018)

### ISSUE THREAD

**Issue by HenricAsk** [TedTolboom/com.xiaomi-mi-zigbee#173]
The switches stops working after a while (all from 1 day to 3 weeks). The only way to fix it (that I have found atleast) is to remove the switch from Homey then readd it again. Then it works for some time again. I have 3 switches installed and all behaves the same.

Running latest Homey firmware 2.5.2
Latest app-version

Best regards
Henric

**Comment by JustThe2ofUs** [comment]
Welcome to Xiaomi. :))
This is the only solution so far.

-- // via mobile //
Am 9. Sept. 2019, 7:34 PM +0200 schrieb HenricAsk <notifications@github.com>:

**Comment by JMeinen69** [comment]
after the last update to v 0.8.0 the double remote switch wont work. It shows up on the homey dashboard and in the app but when push on of the buttons nothing happens. 
How to resolve this? Is deleting and adding it again only option?

**Comment by TedTolboom** [comment]
@JMeinen69 try to add it again without removing.
Will likely result in a "duplicate device" error.. which can be ignored. In most cases the device becomes operational again without having to re-do all flows
