### ISSUE TITLE
Aqara motion sensor not detecting motion 

### ISSUE THREAD

**Issue by arashBaloch** [TedTolboom/com.xiaomi-mi-zigbee#175]
I have had this issue for a week now. The motion detection stops working and after a remove/re-add in homey it only works a few times before it "dies" again. I have the latest homey version: 2.5.2 and the 0.6.0 version of the xiaomi app.

**Comment by Frankman66** [comment]
The same for me. Zigbee signal of the aqara motion sensor seems to be poor. Maybe there is a bug in the driver. For example, the aqara temperature and humidity sensors next and around the motion sensor are working well without any issues. Firmware and xiaomi app are always the latest. Any idears? Thanks.

**Comment by tranceblast** [comment]
I have exactly the same problem as @arashBaloch
