### ISSUE TITLE
Missing condition for Aqara temperature sensor

### ISSUE THREAD

**Issue by davieslobo** [TedTolboom/com.xiaomi-mi-zigbee#176]
Hi, 
The is no "condition" for temperature sensor other than "battery alarm is on". Would it to be possible to add condition "When temperature is" {equal, under, above}?

**Comment by TedTolboom** [comment]
@davieslobo no, this will not be added and is not needed either.
In the flows, you can use a default logic condition card and use the devices temperature tag to check it it is equal, under or above the set threshold.

I expect that this answers your need and will therefore close this issue
