### ISSUE TITLE
Problem with temp after 0.6.1

### ISSUE THREAD

**Issue by pettib** [TedTolboom/com.xiaomi-mi-zigbee#177]
I have 2 Homey installations on different sites with Homey version 2.5.2
After updating to 0.6.1 the temp from Aquara Temp sensor jumps almost 15 degree Celcius up and down several times the last 6 hours.

**Comment by ic3cool** [comment]
Same :(

**Comment by Kjelle1** [comment]
Same here...

**Comment by ic3cool** [comment]
Okej, i did try to remove and added back in. Sensor started to show the temp as bef. upgrade

**Comment by TedTolboom** [comment]
Is fixed in v0.6.2 of the app; waiting app store approval.
