### ISSUE TITLE
Aqara Temperature and Humidity Sensor not reporting

### ISSUE THREAD

**Issue by ronald2404** [TedTolboom/com.xiaomi-mi-zigbee#179]
Hi, 
I have several Aqara Temperature and Humidity Sensor devices, but I noticed that they have issues reporting and like now last report of temperature was 2 days ago.  In the past I have seen this 25 days.  2 days ago I rebooted homey so thats why it is reporting.

Is this known issue? Related to bad zigbee in homey? And how often does the temp normally reports? Is this configurable?

Regards

Ronald

**Comment by axelwathne** [comment]
I had this issue when I had one of them placed in an area with problematic reception. I now have two of them placed fairly close to Homey, and they have been stable for a long time. I used a Cleverio Z-wave thermometer in the problematic location instead. So it's reasonable to think it's related to low level Zigbee problems.

**Comment by JustThe2ofUs** [comment]
As it’s months ago: is there any news or improvement to the „xiaomi sensors stop reporting“ issue?
