### ISSUE TITLE
[Feature Request] Sensitivity option in motion sensor 

### ISSUE THREAD

**Issue by uNiiek** [TedTolboom/com.xiaomi-mi-zigbee#18]
Edit the sensitivity lumen of the device.

**Comment by TedTolboom** [comment]
@uNiiek In order to add this to the drivers parameters, the meshdriver would need to update the attribute reporting and send it to the device...

As far as I'm aware, the Zigbee meshdriver does not have an onOnline trigger for such command...
I'll check with the Athom team for confirmation.
