### ISSUE TITLE
Aqara motion sensor issue

### ISSUE THREAD

**Issue by tranceblast** [TedTolboom/com.xiaomi-mi-zigbee#180]
I have slot of Aqara motion sensors and all of them have the same problem. Sometimes when I pass by the sensor it won't report movement but it report LUX, and sometimes it report movement and not LUX. Look at the pictures, those 2 sensors are placed at the same place and I passed by them, non of them registered movement but registered LUX. Is this related to Homey or app? App version is 0.6.2 
![Screenshot_20191007_145857_app homey](https://user-images.githubusercontent.com/37779210/66315066-57e94080-e915-11e9-92f5-c6433e3703b5.jpg)
![Screenshot_20191007_145908_app homey](https://user-images.githubusercontent.com/37779210/66315077-5ddf2180-e915-11e9-9a9f-722ac2ae3dc3.jpg)

**Comment by chinswain** [comment]
I have the same issue - a stable network of devices is now very unstable, I can't see any reason for it, I've not changed anything hardware or software related.

**Comment by chinswain** [comment]
I have the same issue - a stable network of devices is now very unstable, I can't see any reason for it, I've not changed anything hardware or software related.

**Comment by chinswain** [comment]
Have you managed to resolve this @tranceblast? I have replaced the batteries in all motion sensors and still the same issue (lux updating on motion but no motion update).
