### ISSUE TITLE
Yeelight YLDP09YL

### ISSUE THREAD

**Issue by Elchele74** [TedTolboom/com.xiaomi-mi-zigbee#184]
Hi!

Fisrt of all, thanks for your geat work!!  And, I would like to know if you could consider adding the Yeelight YLDP09YL (ZigBee) to your app?

Have a nice day!

Cedric

**Comment by TedTolboom** [comment]
Can you share a link to the device description?

**Comment by Elchele74** [comment]
Hi!

For an unknown reason I dont see the product on official website, still
available from most markets and reconised on the Xiaomi Home App. Links to
geardbest:

https://www.gearbest.com/smart-lighting-panels/pp_009601353710.html

BRGDS, Cedric



Le ven. 1 nov. 2019 à 13:07, Ted Tolboom <notifications@github.com> a
écrit :

> Can you share a link to the device description?
>
