### ISSUE TITLE
Aqara Wall Switch Single (L) no respond from device.

### ISSUE THREAD

**Issue by guestus** [TedTolboom/com.xiaomi-mi-zigbee#186]
After some time (3 min or more) switch stops work. application dosn't get status and can't switch on/off. As result - "could not reach device" and "timeout" messages. 
But after some time wall switch starts work normaly.
This happednds on Aqara Wall Switch Single (L) and Aqara Wall Switch Double (L).
Other devices works fine  (rellay, temp sensors).

**Comment by MiteZZ** [comment]
Have this problem too, this happens randomly.. The switch ( wall switch double (L)) is well within range of homey.

**Comment by guestus** [comment]
Response from athom:
```
Thank you for reporting this issue!

Unfortunately, this issue concerns an app that is not developed by us, but by a developer in our community.
You can contact the developer of this app via the Appstore. Please report this issue to this developer so he is aware of this issue.

If you have any issues regarding the Homey software or mobile app, feel free to contact us again.
```

**Comment by guestus** [comment]
Found this: Xiaomi Wall Switches (QBKG03LM, QBKG04LM) are detected as routers which they are not.
In https://developer.athom.com/tools/zigbee page they are realy have Router type.

**Comment by guestus** [comment]
One more interesting [thing](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/757)
They are found solution.

**Comment by Telyoussoufi** [comment]
Hi everybody, any news about this issue fix.
i'm facing the same issue , with the 25  Aqara Wall Switchs (no neutral) i bought recently.
unfortunately, i started seriously thinking about changing homey and replacing it by another box :(
