### ISSUE TITLE
Double Wireless Remote Switch (wall switch) sends out double events

### ISSUE THREAD

**Issue by ljsvv** [TedTolboom/com.xiaomi-mi-zigbee#19]
Noticed that my Double Wireless Remote Switch sends out some double events sometimes. Noticed that my Lights are switching on and off straight away.

Made an Homey flow if Button is pressed turn a light on or off.

**Comment by TedTolboom** [comment]
@ljsvv I noticed a similar behavior when using the wireless switch at a longer distance from Homey, without a mesh network... this has been solved by adding a duplicate report time-out...

In a next update, I'll add a similar time-out to the Wireless Remote Switch.

**Comment by TedTolboom** [comment]
@ljsvv as indicated on Slack, I'm not able to reproduce this issue myself.

Current option would be to add a timeout value, but this would potentially create additional issues with other users...

I will first check if filtering on sequence number will become available soon... this would enable the most clean solution. Formally filed a GH issue at Athom (https://github.com/athombv/homey/issues/2157), but this is a known request ...

**Comment by ljsvv** [comment]
Thank you for your response.

We’ll patiently wait for Athom to implement the sequence number filtering option .

**Comment by Maxwell70** [comment]
Thanks for the add! But the switches do not work correctly. Sometimes turns off/on and sometimes not!

**Comment by Maxwell70** [comment]
Thanks for the adding Aqara Light Wall Switch Single/Double! But the switches do not work correctly. Sometimes turns off/on and sometimes not!

**Comment by Maxwell70** [comment]
Single switches all stopped working!

**Comment by TedTolboom** [comment]
@maxwell70 thanks for the feedback, but please add this to a separate issue; adding more details on your issue (app version etc).

This issue is concerning the light wall switch sending a report and due to latency in the network ghosts reports arrive at Homey.

**Comment by Maxwell70** [comment]
@TedTolboom App 0.2.0, homey 1.5.4.-8.
Since last update double switches work better, but sometimes either there is no feedback from the physical enable/disable or I can't enable/disable on Homey.
Single switches were added well! They worked a few times, and then stopped working completely!

**Comment by TedTolboom** [comment]
I inquired for an update at Athom (Emile in person) on what the plans are to complete the Zigbee implementation (and thereby resolve this issue)...

After an extensive discussion to triggered by this question, all I got back was:

weejewel [12:43]
OK! Well, we're working on it slightly_smiling_face

So unfortunately, I cannot provide a more detailed response to my app users.
If you have questions when this will be resolved, please contact Emile directly on slack or by mail....
