### ISSUE TITLE
Problem with the temperature offset

### ISSUE THREAD

**Issue by programmieramt** [TedTolboom/com.xiaomi-mi-zigbee#192]
I have version:  Version 0.7.1.
I want to set an temperture offset for the "lumi.weather" aquara temperture sensor.
But I can not set the offset then any other then "full" numbers. In the description it says you can set 0.7 but it isn't saved.

Best regards,
Sebastian

**Comment by TedTolboom** [comment]
@programmieramt I tried to reproduce, but I can change the value to 0.7 and save it...
Are you sure there is no other setting out of range?
