### ISSUE TITLE
Aqara double switch

### ISSUE THREAD

**Issue by Mbqmannen** [TedTolboom/com.xiaomi-mi-zigbee#194]
wxkg02lm. looses contact again and again with homey.

**Comment by koktaildotcom** [comment]
Confirmed. Looks like it is related with the zigbee not meshing correctly anymore.

**Comment by koktaildotcom** [comment]
Can it be related to: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/186?

**Comment by koktaildotcom** [comment]
Not working anymore again. Looks like its the 25th device and routers doesn't route anymore. 

Cannot unpair and pair them either, only get a timeout.

**Comment by epjjansen** [comment]
Trick is not to delete the double switch device in Homey, but try to add the same device twice. An error message appears: duplicate DeviceID. After this, the device is reporting again.
