### ISSUE TITLE
Problem pairing Aqara motion sensor to Homey pro

### ISSUE THREAD

**Issue by okholter** [TedTolboom/com.xiaomi-mi-zigbee#196]
I have give t a try very many times, but am not able to connect the motion sensor to my homey pro.

**Comment by ifs-dinodona** [comment]
hi same problem

**Comment by epjjansen** [comment]
> I have give t a try very many times, but am not able to connect the motion sensor to my homey pro.

How many Aqara motion sensors (end-device) do you have and how many Zigbee routers do you have?

When you add multiple routers you can have more end-devices. Trick is not to delete the end device in Homey, but try to add the same device twice. An error message appears: duplicate DeviceID. After this, the device is reporting again.

Further, keep your sensors close to your Zigbee router or Homey.
