### ISSUE TITLE
Integration with Chinese Sensors

### ISSUE THREAD

**Issue by BengtCarlsson** [TedTolboom/com.xiaomi-mi-zigbee#197]
Hi!

I have some Aquara sensor bought in China.
I hope your integration is toward both European and Chinese sensors?
But I do not exactly understand the difference.

Peter

Peter.wallin@fapiao.se

**Comment by TedTolboom** [comment]
If it is Zigbee based, and Aqara only has Zigbee based devices, there is no difference between Chinese and European.

“Both” should work for the supported device.

If this answers your question, please close this issue.
