### ISSUE TITLE
Xiaomi motion and door sensors timed out

### ISSUE THREAD

**Issue by biordanescu** [TedTolboom/com.xiaomi-mi-zigbee#198]
Hi, I am unable to set my Xiaomi sensors connected directly - I keep getting 'request timed out' messages

**Comment by devfrey** [comment]
Make sure you keep your sensor as close to Homey as possible. For certain Xiaomi/Aqara devices you need to keep them alive by pressing the reset button every two seconds.

**Comment by ifs-dinodona** [comment]
hi same problem

**Comment by epjjansen** [comment]
> Make sure you keep your sensor as close to Homey as possible. For certain Xiaomi/Aqara devices you need to keep them alive by pressing the reset button every two seconds.

can confirm this
