### ISSUE TITLE
Aqara nodes time out

### ISSUE THREAD

**Issue by geurti64** [TedTolboom/com.xiaomi-mi-zigbee#201]
Since a long time (months) my Aqara nodes are timed out after a reboot. The before last Homey update solved this but since the last Homey update the story continues.
I just tried to re-add a door sensor which didn't work. A Homey reboot gave me all Aqara nodes time out again and only a PtP helped me to add the node.

Note,
Perhaps the reboot was to quick after the before last Homey update which makes me think the problem was solved.

**Comment by ifs-dinodona** [comment]
hi same problem

**Comment by epjjansen** [comment]
Trick is not to delete the end device in Homey, but try to add the same device twice. An error message appears: duplicate DeviceID. After this, the device is reporting again. And you don't have to fix your flows
