### ISSUE TITLE
Can't connect temp sensor and door sensor

### ISSUE THREAD

**Issue by WeZZeY** [TedTolboom/com.xiaomi-mi-zigbee#202]
Hi, I have problems connecting my new door sensor and temperature sensor to the app, I've already connected the same products, but the new ones I've ordered just seem to not be recognized by the app when pairing... 

The temperature sensors I've been able to connect to homey through by adding them to the homey app using the aqara gateway and then connecting that to the MI home homey app. But this doesn't work for the door sensors...

Is there a limit on adding products to the app? I've got 18 devices connected to your aqara homey app, and therefore can't add more?

As stated earlier, these are the exact same devices that I've already got working through the app, but new ones just seems to not be found in pair mode... 

The devices:
https://a.aliexpress.com/_B0ENbx
https://a.aliexpress.com/_BSMrFj

**Comment by WeZZeY** [comment]
18 devices is the limit, when I remove 1 I can add 1, only when I remove the second I can than add another one, and so on...

**Comment by shaarkys** [comment]
Add ZigBee router to your network (usually any non battery powered device) - I'm using IKEA ZigBee repeater and IKEA ZigBee Powersocket and it works fine. Give also 1 week for mesh to stabilize. Other then that, this is rather Homey / ZigBee issue, not relatted to the app itself.

**Comment by epjjansen** [comment]
All Ikea Tradfri bulbs are zigbee routers. I have 32 zigbee devices connected to Homey (pro). 18 routers and 14 enddevices.

Once a while a sensor looses connectivity. 
Solution: 
Trick is not to delete the end device in Homey, but try to add the same device twice. An error message appears: duplicate DeviceID. After this, the device is reporting again. and you don't have to fix your flows again.
