### ISSUE TITLE
 Aqara Wall Switchs (no neutral)

### ISSUE THREAD

**Issue by Telyoussoufi** [TedTolboom/com.xiaomi-mi-zigbee#203]
This is a last call before taking the decision to replace homey by another box :(
i replaced all the wall switchs in my house ( 25 in total) , all no neutral from aqara (single and double ).
as already mentioned in other posts, After some time (3 min or more) switch stops work. application dosn't get status and can't switch on/off. As result - "could not reach device" and "timeout" messages.
But after some time wall switch starts work normaly.
Other devices works fine (rellay, temp sensors).
 i tested the wall switchs with xiaomi gateway , they all works fine
my message is for the app developer , any way you can fix this issue !! ?

**Comment by Guinnex** [comment]
I have exactly the same problem. My switch (no neutral) loose the connexion to homey. Thanks.
