### ISSUE TITLE
Problem now i installed homey FW 5.0.0 rc17

### ISSUE THREAD

**Issue by pjmpessers** [TedTolboom/com.xiaomi-mi-zigbee#208]
Hello Ted.

I recently installed FW 5.0.0 rc17 and the app won't start anymore. I think it's due the change in the zigbee driver. Is it possible to fix it?

**Comment by shaarkys** [comment]
Hi,

TED is aware of this but didn't have time to re-develope it to new SDK. Also is currently enjoying his vacation, so it will take some time.

**Comment by pjmpessers** [comment]
I understand. I hope he enjoys his vacation and i hope that he his still planning to update. In the mean time i wait. ;-)

**Comment by TedTolboom** [comment]
For sure, there will be an update of the Xiaomi / Aqara app; but it will require a substantial amount of work. 
If all goes ok, end of August a first update will be available.

**Comment by pjmpessers** [comment]
Good to hear. Happy this app and the ongoing updates is still alive. I will wait for the update to arrive. 👍

**Comment by DimitryNL** [comment]
First of all, I hope you have had a nice vacation.

I'm on v5.0.0-rc.26 and have the same or probably related issue: v0.8.0 is started but both my Aquara Motion Sensors can't communicate anymore. Suggestion is to update the "Aqara & Xiaomi Zigbee app". If helpful I can send the diagnostics report.

Thanks for all the effort!
