### ISSUE TITLE
Aqara Temperature sensor

### ISSUE THREAD

**Issue by Matarn** [TedTolboom/com.xiaomi-mi-zigbee#209]
I am trying to connect my Aqara sensor but I only get "no app" in homey when I do the pairing. Your app is installed so I don't get it. Can you help me?

**Comment by shaarkys** [comment]
Which version of Homey FW do you have ?

**Comment by Matarn** [comment]
![image](https://user-images.githubusercontent.com/68965510/90315954-caf11980-df1f-11ea-8574-7ad1592dc387.png)

The latest

**Comment by Matarn** [comment]
The latest 

![image](https://user-images.githubusercontent.com/68965510/90316016-258a7580-df20-11ea-9a5e-dccb948a277b.jpeg)

**Comment by shaarkys** [comment]
So revert back as the App is not yet compatible with SDK3 / latest experimental fw.

Please also Close this issue.
