### ISSUE TITLE
Aqara temp sensor does not update

### ISSUE THREAD

**Issue by shcizo** [TedTolboom/com.xiaomi-mi-zigbee#21]
I have paired a temp sensor that dont update its values. It says 18.8 C, 989 mbar, 45,9 % and then nothing happens. Is there a way to troubleshoot this or is it just broken?

**Comment by shcizo** [comment]
I removed it and readded and it works.

**Comment by shcizo** [comment]
Would like to reopen this as the sensor stops updating after a short period of time.

**Comment by TedTolboom** [comment]
@shcizo can you check if this is solved with 1.5.6-RC8 which has just been released to experimental?
You might need to wake the device by pressing the button

**Comment by shcizo** [comment]
I think my issue had more to do with bad reception. i moved it closer to homey and now it updates as it should. i have an aqara door sensor that works fine at the same range though. Anyways, dont think this has anything to do with this app.

**Comment by TedTolboom** [comment]
@shcizo there are reports that WiFi channel 11 can interfere with the ZigBee channels (partly overlapping frequencies)..

You might want to check the WiFi channel your router is using... perhaps this is influencing the range
