### ISSUE TITLE
Add support for Aqara | Opple

### ISSUE THREAD

**Issue by epjjansen** [TedTolboom/com.xiaomi-mi-zigbee#210]
Please add support for the Aqara Opple
This is 2/4/6 way wireless switch
[aqara-opple-smart-switch-review](https://homekitnews.com/2019/12/04/aqara-opple-smart-switch-review/)

6way: WXCJKG13LM 
Producent ID: LUMI
Product ID: lumi.remote.b686opcn01
Device ID: 261
Profile ID: 260

If needed a device can be send to your home for development purposes 
The switch is now added as a unknown zigbee 3.0 device

**Comment by vanrensav** [comment]
@epjjansen doesnt homey see it as button when u press a buttons at adopting? 

Im waiting for adding Opple too!!!

**Comment by TedTolboom** [comment]
It took some time, but with version 1.1.0 support for the Aqara Opple switches is added.
Thank you for your patience and enjoy!
