### ISSUE TITLE
Aqara vibration sensor not added, adding timed out

### ISSUE THREAD

**Issue by Raycokes2000** [TedTolboom/com.xiaomi-mi-zigbee#211]
Hello,

I Have several Aqara vibration sensors but adding timed out. Nothing more no error. Please help.
Gr Ray

**Comment by shaarkys** [comment]
How many ZigBee devices do you have and how many have direct connection to Homey ?
Also which devices you are trying to add - provide the P/N.
But my assumption is that you simply have too many ZigBee devices without having any additional ZigBee router in place.

**Comment by Raycokes2000** [comment]
Not that i know of, where can i check that total? xiaomi mi home gateway asap coming, is underway ;-)

**Comment by shaarkys** [comment]
https://developer.athom.com/tools/zigbee
