### ISSUE TITLE
Add supprot Aqara D1 (Wireless) Switch(es)

### ISSUE THREAD

**Issue by eaasnes** [TedTolboom/com.xiaomi-mi-zigbee#212]
I’m unable to add Aqara Wireless Single Switch (2018). I think it has a new product ID. It has the following Zigbee information: 

![B308BF7B-8489-4AC9-AD9A-52217F89C2A2](https://user-images.githubusercontent.com/70980197/92527437-498f5d00-f227-11ea-98ca-0588481aa146.jpeg)

I’m guessing it’s the same problem with the double switch, but I haven’t got any of those yet so I don’t have the Zigbee information for it.

**Comment by TedTolboom** [comment]
This one is already supported... I guess you are running the experimental Homey release (v5) and the current Aqara app is not (yet) compatible with that version... WIP

**Comment by eaasnes** [comment]
I’m running 4.2.0 of Homey. Any idea why I’m having problems adding the switch? I’ve tried holding it 20-30 cm from Homey and also touching Homey when adding.
 
![9893A3F3-5D4E-4296-935C-B630D1009C9E](https://user-images.githubusercontent.com/70980197/92562273-fabce400-f275-11ea-8987-c37b412177d5.jpeg)

**Comment by epjjansen** [comment]
When you add the wireless switch. Press the button on the switch every 5 seconds. Some devices needs to be kept awake while adding.

**Comment by xternux** [comment]
Is this a know issue with Aqara wireless devices on the homey? 
Does anyone know if this happens when pairing with the Aqara Hub?

**Comment by shaarkys** [comment]
This is known yet in upcoming version (experimental) seems the pairing works already better but Aquara app hasn't been yet ported and Ted is working on that. I would suggest to turn to the discussion forum for further details - https://community.athom.com/t/aqara-xiaomi-smart-home-zigbee-app-v0-8-0/156

**Comment by TedTolboom** [comment]
This is resolved with the release of Homey v5. 

Please note: current app does not work with v5!
I am currently working to make the app compatible with v5 as soon as possible; see updates on the forum.

Ted

**Comment by eaasnes** [comment]
> When you add the wireless switch. Press the button on the switch every 5 seconds. Some devices needs to be kept awake while adding.

Doesn’t seem to help with my switch. Guess I’ll have to wait for the app update. :-)

**Comment by xternux** [comment]
> > When you add the wireless switch. Press the button on the switch every 5 seconds. Some devices needs to be kept awake while adding.
> 
> 
> 
> Doesn’t seem to help with my switch. Guess I’ll have to wait for the app update. :-)

You can try restarting the homey from the Homey app and then try to pair it when the ZigBee module is up and running again. Worked for me on the 4.2.0 version (Homey Pro early 2019).

**Comment by eaasnes** [comment]
> > > When you add the wireless switch. Press the button on the switch every 5 seconds. Some devices needs to be kept awake while adding.
> > 
> > 
> > Doesn’t seem to help with my switch. Guess I’ll have to wait for the app update. :-)
> 
> You can try restarting the homey from the Homey app and then try to pair it when the ZigBee module is up and running again. Worked for me on the 4.2.0 version (Homey Pro early 2019).

Tried it now, but still didn’t work for me. Do you have the b186acn**02** switch also?

**Comment by xternux** [comment]
> > > > When you add the wireless switch. Press the button on the switch every 5 seconds. Some devices needs to be kept awake while adding.
> 
> > > 
> 
> > > 
> 
> > > Doesn’t seem to help with my switch. Guess I’ll have to wait for the app update. :-)
> 
> > 
> 
> > You can try restarting the homey from the Homey app and then try to pair it when the ZigBee module is up and running again. Worked for me on the 4.2.0 version (Homey Pro early 2019).
> 
> 
> 
> Tried it now, but still didn’t work for me. Do you have the b186acn**02** switch also?

Hmm. Looks like I have the b186acn01 and b286acn01. Didn't know there was a new version.

**Comment by eaasnes** [comment]
> Hmm. Looks like I have the b186acn01 and b286acn01. Didn't know there was a new version.

Ok, then I still have to wait for the update ;-)

**Comment by Lansuper** [comment]
For me the same problem, article number On the back is WXKG07LM. Double remote switch.
Pairing works, but gives ‘unknown device’. Keep alive is not the solution here...

**Comment by eaasnes** [comment]
Did some testing, and finally managed to get it working for me. The only change I did was to the productId in the driver.compose.json file in the drivers/remote.b186acn01 folder. Changed the last number of the ID from 1 to 2:
`"productId": "lumi.remote.b186acn02",`
This most probably breaks the acn01 switch, but that doesn't matter to me since I don't have any of those.

**Comment by TedTolboom** [comment]
This the D1 series of the Aqara (wireless) switches; which I will add to the app, once the initial bugs are solved.

**Comment by TedTolboom** [comment]
With version 1.1.0 support for the full range of Aqara D1 (wireless) switches is added.
Thank you for your patience and enjoy!
