### ISSUE TITLE
Xiaomi Wireless Switch added as Basic Zigbee Device

### ISSUE THREAD

**Issue by ferdyh** [TedTolboom/com.xiaomi-mi-zigbee#215]
Seems like Homey is unable to recognize the right device for my Xiaomi Wireless Switch and adds it as a Basic Zigbee device.
Running app version 0.8.0 and Homey version 5.0.0-rc.34.

**Comment by shaarkys** [comment]
@ferdyh this app is not yet compatible with Homey on experimental firmware version.
Please close this issue and wait for official update.
Thanks.

**Comment by TedTolboom** [comment]
Closed: should be resolved in v1.0.0
