### ISSUE TITLE
Inclusion starts automatically without using the sensor's button

### ISSUE THREAD

**Issue by Tequila329** [TedTolboom/com.xiaomi-mi-zigbee#218]
Hi, 

when i try to include a new temp sensor, the inclusion process is always starting automatically. 
Select the device i want to include and after one second, the "device is being added" dialog shows up without using the button on the sensor. After a few seconds, i get the "device stopped responding..." dialog. 

- Homey is rebooted after installing the new app version. 
- I tried with different types of sensors, always the same behavior.

**Comment by TedTolboom** [comment]
Hi @Tequila329,

On which Homey version and app version are you working?
I have never seen this behavior with a battery powered device. Are you sure that a battery powered device is causing this; or is another mains powered  Zigbee device causing this?

**Comment by Tequila329** [comment]
Homey firmware is 5.0.0.RC34.
App Version 1.0.0

But i can think we can close this here. When i try to add a INNR Zigbee Plug, i get the same behavior. The Xiaomi devices was just the first one I tried.

But let me say thank you for your excellent work and all the time you spent on this project!

**Comment by TedTolboom** [comment]
@Tequila329 thank you for the feedback.
I would recommend to check if your have any powered Zigbee that might be searching for his node (so previously connected to Homey or something like that).
