### ISSUE TITLE
Xiaomi Light Sensor: Battery status incorrect

### ISSUE THREAD

**Issue by MarcoGos** [TedTolboom/com.xiaomi-mi-zigbee#220]
On both of my Xiaomi Light Sensors report an empty battery. Battery alarm goes off and the battery level shows nothing (no percentage). Before the update to v5 both shown 100%. All other sensors are working fine.
![IMG_0734](https://user-images.githubusercontent.com/44016861/94807235-a5e13900-03ef-11eb-863c-6dec09bfbc0c.PNG)
![IMG_0735](https://user-images.githubusercontent.com/44016861/94807249-aa0d5680-03ef-11eb-855b-9fb100d1ab47.PNG)

**Comment by TedTolboom** [comment]
Fixed in 1.0.1 (in app store). A removal and re-inclusion of the sensor is required to fix it.
Please re-open if not fixed
