### ISSUE TITLE
Problem Aqara Wireless Switch Singel (2018) SDK 3

### ISSUE THREAD

**Issue by nissenhj** [TedTolboom/com.xiaomi-mi-zigbee#221]
Aqara Wireless Switch Singel (2018) but if i do a long press nothing happens.

I try to uninstall one and then install it again. But if I select "A scene has been activated" and select objects, then a black image with the text "No results" appear, here I could before select long press and double press.
Now I can only select the option "A button has been pressed"

I hope there is a solution to this?
![Screenshot_20201001-182524](https://user-images.githubusercontent.com/45319576/94839750-b9a09580-0417-11eb-872a-e6e45f466321.png)
![Screenshot_20201001-182532](https://user-images.githubusercontent.com/45319576/94839762-bdccb300-0417-11eb-8843-d6c56b22724d.png)
![Screenshot_20201001-185249](https://user-images.githubusercontent.com/45319576/94839774-c1f8d080-0417-11eb-92b9-3e4d2e93cc26.png)
![Screenshot_20201001-185317](https://user-images.githubusercontent.com/45319576/94839782-c4f3c100-0417-11eb-8cd9-7811ff371c15.png)

**Comment by TedTolboom** [comment]
Thanks for reporting. Found the issue and will be fixed in 1.0.1

**Comment by TedTolboom** [comment]
Fixed in 1.0.1 (in app store). Please re-open if not fixed
