### ISSUE TITLE
[Feature] Xiaomi smoke sensor - Add smoke density capability

### ISSUE THREAD

**Issue by shaarkys** [TedTolboom/com.xiaomi-mi-zigbee#226]
Even Christmas will be in more then 2 months, may I make a wish? Would it be possible to get also Smoke density reported please?

![SmartSelect_20201008-112249_Homey](https://user-images.githubusercontent.com/14859895/95441013-eb56b680-0959-11eb-92a8-5b974f5dc0a6.jpg)

**Comment by shaarkys** [comment]
Also this is the code details from MaxMudjon - https://github.com/Maxmudjon/com.maxmudjon.mihomey/blob/master/drivers/smoke_sensor/device.js  ... but this will probably not help, right.

` if (device["data"]["density"]) {
      this.updateCapabilityValue("measure_smoke_density", parseInt(device["data"]["density"]));
    }`

**Comment by TedTolboom** [comment]
Thanks, already found some lead at another Xiaomi Zigbee implementation (other platform) where this information is originating from...

**Comment by TedTolboom** [comment]
Available as of v1.1.3

**Comment by shaarkys** [comment]
bef20cf7-e275-403c-a356-f76afc3b599d

One of four sensors on 1.1.3 is not showing smoke density icon/option - possibly Athom bug?

**Comment by TedTolboom** [comment]
Can you try what happens after a second app restart?

**Comment by shaarkys** [comment]
It's ok after 2nd restart, thank you ! :-)
