### ISSUE TITLE
Heb ik de verkeerde switch gekocht

### ISSUE THREAD

**Issue by MarcelScheffer** [TedTolboom/com.xiaomi-mi-zigbee#232]
Hallo, ik heb de Aquara wireless double switch aangeschaft. Zonder te kijken naar typenr..... Typenr is WXKG07LM. Hoe kan ik deze koppelen? Of heb ik pech:( Marcel Scheffer

**Comment by TedTolboom** [comment]
@MarcelScheffer i do assume you are using Homey v4.2 (stable) and you bought the Aqara D1 series double wireless switch?

In the current Aqara app for v4.2, this switch is not supported.
Support has been added to the Aqara app for v5, currently available as test version.

**Comment by MarcelScheffer** [comment]
@TedTolboom Thanks for your message! I wait for the stable version.
