### ISSUE TITLE
Manual mode not available

### ISSUE THREAD

**Issue by Polder1987** [TedTolboom/com.xiaomi-mi-zigbee#234]
For the aqara b1 curtain controller, I’m missing some settings that appear the be available/functionality for this system. It should be able to set the “manual mode”, meaning when you manually pull the curtain it should trigger the motor to do the rest. Is it possible to make this feature available? Volunteer for testing

**Comment by TedTolboom** [comment]
That’s correct; still on my todo list, as communicated on the forum

**Comment by TedTolboom** [comment]
Testing this setting right now... expected to become available in the next update

**Comment by Polder1987** [comment]
Thank you for the update, exited. Again happy to test and provide feedback. Best

**Comment by TedTolboom** [comment]
Added to v1.2.3; available in the app store test environment: https://homey.app/a/com.xiaomi-mi/test/
Manual mode, reverse direction settings and maintenanceAction to reset the track limits

Will close this issue assuming resolved; if not please re-open

**Comment by Polder1987** [comment]
Perfect, tested and it works. Just a small comment (but this might be due to the fact that the update comes after connection the B1 to homey). The setting for manual mode was TRUE by default. Although the setting in the motor is not TRUE by default and therefore a mismatch between homey visual setting and the actual setting of the B1.  So I had to set the settings in the homey device to FALSE, save, change to TRUE, save. Then it works...
