### ISSUE TITLE
Xiaomi Light Sensor - settings?

### ISSUE THREAD

**Issue by shaarkys** [TedTolboom/com.xiaomi-mi-zigbee#237]
Hi @TedTolboom , are those intentional settings for Xiaomi Light Sensor? Will include picture...not working from mobile.

**Comment by shaarkys** [comment]
![SmartSelect_20201123-155441_Homey](https://user-images.githubusercontent.com/14859895/99980224-488eb600-2da8-11eb-840f-2e7e8ede1c1a.jpg)

**Comment by Patrick1610** [comment]
Hi @shaarkys, How where you able to add the sensor? I get the message 'No compatible Homey App has been found for this device. It has been added as a Basic Zigbee device.' In this state, it is a button which does nothing (receive no value's as wel..)

**Comment by shaarkys** [comment]
And you are on v5 firmware?

**Comment by Patrick1610** [comment]
No, still on 4. Should it work better on 5? 
Little bit anxious for using a beta version for my entire home..

**Comment by shaarkys** [comment]
It depends, if this is the case, better wait for "stable". Current v5 is on RC49 (yes, 49 release candidates...). More info on forum, here it is OT unfortunately...

**Comment by TedTolboom** [comment]
Redundant settings removed
