### ISSUE TITLE
Aqara Curtain motor and IKEA remote

### ISSUE THREAD

**Issue by torroa** [TedTolboom/com.xiaomi-mi-zigbee#238]
_Any_ IKEA remotes paired with Homey interacts with the Homey paired Aqara Curtain motors when the on/off button is pressed - even if no flows with the corresponding remote are made.

If the on/off button, or the on-or-off button is pressed, the curtains alternate between open and closed.

**Comment by TedTolboom** [comment]
that is specific behavior of the Ikea remote... whom will be searching for lights (with onoff capability) upon inclusion.
also happened with the Aqara Opple remotes, when not set in the right mode during inclusion.

This is nothing I can change from within the Aqara app.
Therefore, I will close the issue.
