### ISSUE TITLE
Aqara Door / window sensor wont add in homey

### ISSUE THREAD

**Issue by fishbananaa** [TedTolboom/com.xiaomi-mi-zigbee#241]
Im trying to add 2 aqara window / door sensors through homey. But when I hold the button as instructed, everytime it just says «status not ready»

I have tried restarting homey and the app. And reinstalling the app but getting the same issue everytime. Im holding the device very close to homey and have tried multiple times for several hours. 

What am I doing wrong or is there a bug?

**Comment by TedTolboom** [comment]
The status «status not ready» indicates that the Zigbee chip is not ready. Not related to the app.

IF that is persistent after a reboot or Pulling the Plug (disconnecting the power source of Homey for several minutes), then I would contact Athom support to resolve this; there is a specific recovery process to follow

**Comment by TedTolboom** [comment]
Stale... closing issue
