### ISSUE TITLE
Cannot add Aqara Water Sensor

### ISSUE THREAD

**Issue by olliman636** [TedTolboom/com.xiaomi-mi-zigbee#246]
Hello,

I bought six Aqara Water Sensors and after adding three of them to Homey I cannot add any other zigbee devices. I have twelve zigbee devices connected directly to Homey without any zigbee router. 

When I try to add the other three Aqara Water sensors (or any other zigbee devices) the "add a new device wizard" stays at "Pinch the sensor for 5 seconds until the blue light flashes continuously" and nothing happens. 

Diagnostic Report App: 14db01b0-c7fe-4750-8031-043ae45ea1a3

Thank you and greetings from Vienna,
Olliman

**Comment by shaarkys** [comment]
1. Reboot Homey
3. Wait until it's fully booted and all devices available
3. Restart Aqara & Xiaomi ZigBee App and wait until all Zigbee are available
4. Try to add Aqara Water Sensor again....

If it fails, try to exchange battery from sensor or disconnect it for a while.

...naturally I assume you are on v5 Homey firmware - I had to perform this exactly for all Water sensors I have been re-adding recently.

**Comment by olliman636** [comment]
> 1. Reboot Homey
> 2. Wait until it's fully booted and all devices available
> 3. Restart Aqara & Xiaomi ZigBee App and wait until all Zigbee are available
> 4. Try to add Aqara Water Sensor again....
> 
> If it fails, try to exchange battery from sensor or disconnect it for a while.
> 
> ...naturally I assume you are on v5 Homey firmware - I had to perform this exactly for all Water sensors I have been re-adding recently.

**Comment by olliman636** [comment]
Thanks for your answer. I solved the problem resetting the whole Zigbee stack from Homey. 

Thank you and greetings from Vienna
Olliman
