### ISSUE TITLE
Aqara roller shade not supported 

### ISSUE THREAD

**Issue by MevilVoronkevich** [TedTolboom/com.xiaomi-mi-zigbee#250]
Please add support Aqara roller shade

**Comment by BartMarien** [comment]
I would also love to see the Aqara smart roller shade controller on the supported devices list :-)

See:
https://www.aqara.com/en/product/smart-roller-shade-controller

SRSC-M01

**Comment by shaarkys** [comment]
As you may have noticed, it has been added by Ted. You can close this issue.
