### ISSUE TITLE
Warning when opening Aqara double relay - LLKZMK11LM 

### ISSUE THREAD

**Issue by Rstorm36** [TedTolboom/com.xiaomi-mi-zigbee#251]
@TedTolboom,

After update to homey firmware 5, I receive the following warning while opening Aqara double relay LLKZMK11LM:" Dit apparaat wordt wellicht niet meer ondersteund in de toekomst".

Is this message linked to the aqara app? Or is this caused by an other issue? 
I hope these devices will still available I use multple of these. 

![Screenshot_20210405-070500](https://user-images.githubusercontent.com/81950567/113762060-7867a600-9718-11eb-81dd-d510719c2b38.jpg)

Is there a possibility to solve this?

**Comment by shaarkys** [comment]
See message from TED - https://community.athom.com/t/aqara-xiaomi-smart-home-zigbee-app-v0-8-0-test-v1-2-5/156/2843?u=sharkys

Please close it, thank you.

**Comment by Rstorm36** [comment]
Thanks for the respons
