### ISSUE TITLE
Aqara Wireless remote switch h1 double rocker

### ISSUE THREAD

**Issue by DavyBert** [TedTolboom/com.xiaomi-mi-zigbee#258]
Hello,

I bought an aqara dual remote zigbee switch.
Howerver the H1 double rocker is not in the long great supported devices list. I did not know there where new types.

Or do i do something wrong?

Most of my devices are aqara and these works great thanks to the aqara app on homey :)

**Comment by DavyBert** [comment]
lumi.remote.b28ac1
--

**Comment by TedTolboom** [comment]
Has been added in v1.3.4; currently in the app store.
Will close the issue; if unresolved, please re-open

**Comment by DavyBert** [comment]
Hello,

I´ve noticed this and i can confirm it works.
I will buy you a beer 🍺

Thanks
Davy Bert

Op ma 27 sep. 2021 09:48 schreef Ted Tolboom ***@***.***>:

**Comment by TedTolboom** [comment]
Cheers mate; appreciate that!

**Comment by DavyBert** [comment]
The beer has been served 😀

Thanks for adding

Op ma 27 sep. 2021 18:58 schreef Ted Tolboom ***@***.***>:
