### ISSUE TITLE
Add support for Mijia Aqara Water Sensor

### ISSUE THREAD

**Issue by TedTolboom** [TedTolboom/com.xiaomi-mi-zigbee#26]
Add support for:
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mijia-aqara-water-sensor/

**reference info:**
Xiaomi partnumber: SJCGQ11LM
"manufacturerName": "LUMI",
"productId": "lumi.sensor_wleak.aq1",
"deviceId": 1026,
"profileId": 260,

**Comment by TedTolboom** [comment]
Waiting on Athom to implement ZigBee Intrusion Alarm Zones, leading issue:
https://github.com/athombv/homey/issues/2005

**Comment by chinswain** [comment]
Mine arrived today so will test when Athom sort out #2005

**Comment by TedTolboom** [comment]
I inquired for an update at Athom (Emile in person) on what the plans are to complete the Zigbee implementation (and thereby resolve this issue)...

After an extensive discussion to triggered by this question, all I got back was:

weejewel [12:43]
OK! Well, we're working on it slightly_smiling_face

So unfortunately, I cannot provide a more detailed response to my app users.
If you have questions when this will be resolved, please contact Emile directly on slack or by mail....

**Comment by TedTolboom** [comment]
> I have received today 2 water sensors and they both don't work with this app.
> Athom is very slow with updates and fixing problems.

@Emile86 To set the right expectations. Athom will rewrite Zigbee after 2.0 has been released... 
likely (not confirmed) with the 2.1 release.

**Comment by Emile86** [comment]
Sad to hear that. Especially that i don't think that they will release 2.0 before end of the year. 
For 2.1 it will be a long story I'm afraid. 
Thank you for clear answer.

**Comment by bliekp** [comment]
Ah, thanks for the reference to this one. Sorry I missed this one.
How unfortunate that Athom is -once again- very slow in fixing things... I should have checked before I bought this thing though...

**Comment by Designburo** [comment]
The zones that have just been introduced into the homey.. was that what we were waiting for ?

**Comment by Thenorneron** [comment]
Kinda disappointed Athom is working on irrelevant  things while whole zigbee update is just waiting...

**Comment by TedTolboom** [comment]
@designburo we’re still waiting for the Zigbee rewrite AND implementation of the alarm cluster by Athom. No signs yet of both.

**Comment by MatsAnd** [comment]
Hi - any news on this from Athom?

**Comment by ludwich** [comment]
Any news? Can we as customers do anything to make them speed it up?

**Comment by Hihaj** [comment]
@TedTolboom I heard that the long-awaited Zigbee rewrite is expected to be released in the coming months together with the SDK version 5. Do you know if that includes everything needed to support the flood sensor?

**Comment by TedTolboom** [comment]
@Hihaj yes, you likely have received the mail regarding the soon to arrive Zigbee update (Homey v5.0.0 and SDK3).
On the forum topic, I already posted a message to manage all expectations: https://community.athom.com/t/aqara-xiaomi-smart-home-zigbee-app-v0-8-0/156/1817

Rebuilding the Xiaomi/ Aqara zigbee app based on SDK3 will be quite some work to do this without impact to ˜10.000 users; to only get the existing devices (with existing functionality) working on Homey v5. As mentioned on the forum, I don't expect to be able to release an initial version before my holidays break. Please keep in mind that my releasing an initial version will trigger quite some people to update to the experimental release....

Once existing device support is secured, I will be able to start extending the device support for new devices like the water sensor... 

To answer your question ("Do you know if that includes everything needed to support the flood sensor?") directly: 
Yes, from what I see the new Zigbee core is quite versatile to implement manufacturer specific options and will provide the opportunity for me to add support for the water sensor.

**Comment by TedTolboom** [comment]
It took some time, but with version 1.1.0 finally support for the Aqara water leakage sensor is added.
Thank you for your patience and enjoy!
