### ISSUE TITLE
Opple 6 Button Switch - Release trigger not working after more that 5 seconds

### ISSUE THREAD

**Issue by mvanlijden** [TedTolboom/com.xiaomi-mi-zigbee#263]
I've just received the Opple 6 button switch and tried to map all functions in Homey.
I am running v1.3.0 of the app on Homey v7.1.1

All triggers (1,2,3 clicks, long press) work fine, except the release trigger. I've tried many timings, also with stopwatch next to it.
Long press triggers after 2 seconds of pressing (at least at time my notification comes in)
But the release trigger only triggers if I release the button within 5 seconds after pressing the button, so 3 seconds after the long press is triggered. Keeping the button pressed longer than that and releasing it will not trigger the release anymore.

Is this behavior based on the Opple behavior or is this a bug in your app?

**Comment by TedTolboom** [comment]
This is a device limitation; after more than 8 seconds holding the button, the device will reset itself.
I can't change this behavior.
