### ISSUE TITLE
Aqara Wireless Mini Switch homey Bridge Beta 

### ISSUE THREAD

**Issue by kimc88** [TedTolboom/com.xiaomi-mi-zigbee#264]
Hi a few days ago I could well add Aqara Wireless Mini Switch but now it has been removed from the homey bridge Beta. So how do I add it now?
![aqara-wireless-mini-switch-bezprzewodowy-wlacznik-aqara-mini-switch-main-iShack](https://user-images.githubusercontent.com/3104661/134681226-6a0a4f1b-5991-4a3f-a553-3f83851e4b0d.jpg)
![Screenshot_20210923-204050](https://user-images.githubusercontent.com/3104661/134681233-b404f39d-c451-4496-9777-263aa355a654.jpg)

**Comment by TedTolboom** [comment]
Should be fixed in v1.3.4 currently being pushed to the app store.
If not, please re-open the issue
