### ISSUE TITLE
Aqara Smart Plug new device not pairing

### ISSUE THREAD

**Issue by m3ngi3** [TedTolboom/com.xiaomi-mi-zigbee#266]
https://homey.app/en-us/store/product/Xiaomi-Aqara-Smart-Plug/

V.1.3.8

Connect button over 5 seconds: 1 red blink and then fast blue blinking (instead of 3 solid blue blinks)

Homey wizard is not seeing / adding device

**Comment by TedTolboom** [comment]
Is there an error code shown in the Homey app? 
Or can you describe what information is shown in the Homey app, after the instruction to press the button for 5 seconds?

**Comment by m3ngi3** [comment]
![image](https://user-images.githubusercontent.com/47530580/139957610-d8d43f6a-5ae0-4eec-92ce-0082fd147d23.png)

**Comment by m3ngi3** [comment]
![image](https://user-images.githubusercontent.com/47530580/139957642-a7f0d730-bf17-410e-aaec-433746efe2a8.jpeg)

**Comment by m3ngi3** [comment]
I wait...
The blue led on smart plug stops blinking.
Homey app stays in instruction screen.

**Comment by TedTolboom** [comment]
It doesn't go beyond the screenshot as you shared; so no "a device is being added"?
Can you pull the plug from it's socket, start the process to add the plug to Homey, until it shows the above mentioned screen and THEN put the plug back into the socket. No need to press the button.

**Comment by m3ngi3** [comment]
It indeed stays in the instruction screen shown above. No change.
The instruction states that after the 5 second press, a red blink and 3 blue blinks should follow. However after the red blink, the blue led blinks fast for a period of time and then shuts down. Homey wizard does not respond at all.

When removing smart plug from socket and re-inserting, blue blink only once. Homey wizard no response.

**Comment by m3ngi3** [comment]
Oh my God!
Did a restart of the Homey Pro and plugs added fine...
Can't believe I work in IT 😅

**Comment by m3ngi3** [comment]
"Did you try to turn it off and on again ??"

**Comment by TedTolboom** [comment]
In that case, it was in fact an issue with Homey’s Zigbee not being ready / accepting new devices
