### ISSUE TITLE
Add support for MiJia Honeywell Smoke Detector

### ISSUE THREAD

**Issue by TedTolboom** [TedTolboom/com.xiaomi-mi-zigbee#27]
Add support for:
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mijia-honeywell-smoke-detector-white/

**reference info:**
Xiaomi partnumber: ?
"manufacturerName": "LUMI",
"productId": "lumi.sensor_smoke",
"deviceId": 1026,
"profileId": 260,

**Comment by TedTolboom** [comment]
Waiting on Athom to implement ZigBee Intrusion Alarm Zones, leading issue:
athombv/homey#2005

**Comment by TedTolboom** [comment]
I inquired for an update at Athom (Emile in person) on what the plans are to complete the Zigbee implementation (and thereby resolve this issue)...

After an extensive discussion to triggered by this question, all I got back was:

weejewel [12:43]
OK! Well, we're working on it slightly_smiling_face

So unfortunately, I cannot provide a more detailed response to my app users.
If you have questions when this will be resolved, please contact Emile directly on slack or by mail....

**Comment by gizmodok** [comment]
Hi, Homey developers have implemented version 2.0 of there software is there possibility that " ZigBee Intrusion Alarm Zones" are there implemented?

**Comment by chinswain** [comment]
Not yet, hopefully Athom will make the required changes soon.

**Comment by MiteZZ** [comment]
Is there any progress regarding this issue?

**Comment by psy0rz** [comment]
@MiteZZ we're still waiting on Athom, see https://github.com/athombv/homey-apps-sdk-issues/issues/79

**Comment by TedTolboom** [comment]
It took some time, but with version 1.1.0 finally support for the Xiaomi Honeywell smoke sensor is added.
Thank you for your patience and enjoy!
