### ISSUE TITLE
Aqara motion sensor

### ISSUE THREAD

**Issue by eeckelaertyannick** [TedTolboom/com.xiaomi-mi-zigbee#292]
My aqara motion sensor was working fine but I removed it en included it again sinds then this dos not work I can not re includ it. Could you please advice, I see that there are others hi have same troubles some fixed it others not. I can not fix it. Seems like the inclusion function won't work in the app.

End I still have a p1 version ho I can not included ether.

**Comment by TedTolboom** [comment]
Motion sensor P1 can be included in v1.6.0
