### ISSUE TITLE
Aqara Motion Sensor P1

### ISSUE THREAD

**Issue by michaelleuzinger** [TedTolboom/com.xiaomi-mi-zigbee#298]
The Motion Sensor P1 gets not recognized and shows up as „unknown zigbee device“ when trying to add it as a (or the) „Motion Sensor“ (which obviously it isn’t but the „Motion Sensor P1“) in the Homey App. 

The url to the product page is: https://www.aqara.com/en/product/motion-sensor-p1

**Comment by JurGrady** [comment]
I have exactly the same issue.

**Comment by skymania** [comment]
Motion sensor P1 uses different cluster (vendor specific) to report illumination / motion detection, so it will not work with existing "Motion Sensor" driver.

**Comment by TedTolboom** [comment]
Released in v1.6.0
