### ISSUE TITLE
Add support for the Aqara Smart Curtain Controller 

### ISSUE THREAD

**Issue by TedTolboom** [TedTolboom/com.xiaomi-mi-zigbee#30]
Add support for:
https://xiaomi-mi.com/sockets-and-sensors/xiaomi-aqara-smart-curtain-controller-white/

**reference info:**
Xiaomi partnumber: ZNCLDJ11LM
"manufacturerName": "LUMI",
"productId": "lumi.curtain",
"deviceId": 514,
"profileId": 260,

**Comment by LyoshaDovolen** [comment]
really need this

**Comment by Buka20** [comment]
+1

**Comment by Maxwell70** [comment]
+1

**Comment by permadm** [comment]
+1

**Comment by StasKorecky** [comment]
+1

**Comment by onaggm** [comment]
+1

**Comment by corsaroff** [comment]
+1

**Comment by Sapadi** [comment]
+1

**Comment by bumer0** [comment]
+1

**Comment by sprut666666** [comment]
+1

**Comment by KVolkov87** [comment]
+1

**Comment by meyland** [comment]
+1

**Comment by TedTolboom** [comment]
Dear all,

See my call for community support on the Homey community forum: https://forum.athom.com/discussion/comment/69566/#Comment_69566

**Comment by TedTolboom** [comment]
v0.4.0, including support for the Aqara Curtain Controller, has been uploaded to the app store for approval.
I'll close this issue, this this enhancement request is fullfilled.

**Comment by ashleywolf87** [comment]
Hi guys I'm new with the whole business with Homey and its customization. May I know if the Xiaomi Gateway is needed for Homey to control this Aqara Curtain Motor ZNCLDJ11LM?
