### ISSUE TITLE
Aquara Human Body Sensor not active after being triggered

### ISSUE THREAD

**Issue by EDVDVD** [TedTolboom/com.xiaomi-mi-zigbee#34]
The sensor does not respond to movement for some time after the motion alarm has been triggered.
I for example have the disable motion alarm on 30 seconds, then for around 5 to 10 seconds the sensor motion does not trigger again.
So it has a period of time it does not register any motion, I have this on 2 Aquara Human Body Sensors.
I use it with the countdown app, but sometimes becouse it does not trigger motion again the countdown ends and lights go off while i am in the room.

Is this a known issue?, I read more people have it on the athom forum but never a solution.

**Comment by cbho** [comment]
Hi,
There's a limit of 60 sec, unfortunately...
https://forum.athom.com/discussion/4373/how-to-count-people-going-up-down-stairs

**Comment by TedTolboom** [comment]
As also commented in the forum: https://forum.athom.com/discussion/comment/67188/#Comment_67188

I also recently learned that the sensors have 2 different modes:
Normal and test mode, as described in the FAQ of Gearbest:
![image](https://user-images.githubusercontent.com/17163431/36244144-5a9fb408-1225-11e8-8db1-bbd6368cfd86.png)

This does explain why the sensors work with 5 second interval directly (first 2 hours) after inclusion and when the button has been pressed... and fall back to the 1 minute interval after the 2 hours.

So this is a device (firmware) limitation.
I'll update the minimum interval value in the next update accordingly and will close this issue.
