### ISSUE TITLE
Maintainer MIA (Fork?)

### ISSUE THREAD

**Issue by linde12** [TedTolboom/com.xiaomi-mi-zigbee#343]
Maintainer seems to be MIA. Last merge was in November 2022 and there have been tons of PRs and issues created since that have yet to be addressed. Anyone got a fork going?

@TedTolboom please correct me if i'm wrong 👍

**Comment by TedTolboom** [comment]
You're wrong. See forum topic

**Comment by linde12** [comment]
> You're wrong. See forum topic

Which one?
