### ISSUE TITLE
Aqara Wireless Switch

### ISSUE THREAD

**Issue by dkduck** [TedTolboom/com.xiaomi-mi-zigbee#38]
Just bought Xiaomi Aqara Wireless Switch and connected to the Homey.
It then adds as an unknown device, with a standard Zigbee icon

**Problem:**
Added as an unknown device

**Link to device:**
https://www.aliexpress.com/item/2017-Xiaomi-Aqara-Multifunctional-Smart-Wireless-Switch-Intelligent-Mihome-APP-control-wireless-key-for-iPhone-Xiaomi/32816836631.html?spm=a2g0s.9042311.0.0.SVOluK

**Screenshot:**
![xiaomiaqarawirelessswitch](https://user-images.githubusercontent.com/36172135/35827039-ef428f30-0aba-11e8-9239-a84f9c98e282.JPG)

**What I would like:**
To use it as a switch to turn on/off lights in flows

I understand that the switch likely isen´t supported, since I understand there could be different models, correct me if I´m wrong.
Hope for your help :-)

And thanks in advance
Erik

**Comment by TedTolboom** [comment]
Hi Erik,

Indeed Product ID's are different to the ones currently supported...
I will need to add this product ID in a next update (will be after this week)...

Would you be able to test a separate version (install via Command Line); because it could be that the version difference also points to a different firmware version (and behavior)....

**Comment by chinswain** [comment]
@TedTolboom I have one of these arriving shortly, I'll report back if it doesn't work.

**Comment by dkduck** [comment]
Hi Ted

Just let me know when, I’ll try to help you as good I can.

**Comment by dkduck** [comment]
Btw Ted, first time I did a Github issue, is it ok written?

**Comment by moekdegroot** [comment]
He Ted, I too just received some wireless single switches and I think they also have a different product ID. They are added and recognized but only a single click is working.
You want me to create a separate issue for these ID's or is this post sufficiënt?
Best, Moek
![aqara](https://user-images.githubusercontent.com/16590284/36060520-6cb29fd0-0e4b-11e8-8e13-d6a12b12590d.png)

**Comment by TedTolboom** [comment]
@dkduck yes, would love if every first time GitHub issue is structured like this...
Just checking... the original ID is `lumi.sensor_switch.aq2` and the ID you reported is `lumi.sensor_swit`...

Which doesn't make sense. As far as I can see, Xiaomi would not shorten the name (`switch` to `swit`) and only add an attribute like `.aq2`...

I think something might gone wrong during the inclusion of the switch... can you try to remove the switch and re-include it at close proximity of Homey?

**Comment by dkduck** [comment]
@TedTolboom  - Tried from 10 cm distance and same result, see picture

![unknownzigbee](https://user-images.githubusercontent.com/36172135/36265878-77c1947a-1270-11e8-846c-2868c19b0d7e.JPG)

**Comment by TedTolboom** [comment]
@dkduck can you let me know if the issue has been solved with v0.2.4 as is now available in the app store?

**Comment by dkduck** [comment]
@TedTolboom, works great with inclusion, but when making simple flow to turn on a single lamp nothing happens

**Comment by TedTolboom** [comment]
@dkduck are you able to run the app in debug mode via the Command Line, so that the received data can be shown?

**Comment by dkduck** [comment]
@TedTolboom  Sure, if you tell me how to do :-)

**Comment by dkduck** [comment]
@TedTolboom  You can close this, it´s included as it should be, so nice job :-)
But, the switch is defect...

**Comment by TedTolboom** [comment]
@dkduck lol... Just figured out that you do have a special version of the Aqara Wireless switch... 

namely the Aqara Wireless Switch with gyro sensor...
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/42

It’s name is lumi.sensor_switch.aq3 but the device identifier is set as lumi.sensor_swit...

You might experience that it will not trigger on 3x and 4x click.. but it will trigger on a shake event...

I’ll add the right support in the next update

**Comment by dkduck** [comment]
@TedTolboom lol - that explains a lot :-)
Looking forward to next update according to #42 

Just still dosen´t explain why 1 or 2 click still not working, but maybe in the update, thanks and keep up the brilliant work you do :-)

**Comment by TedTolboom** [comment]
It maken perfect sense...
Because, now I have the device,I discover that this version sends a different attribute report... which I didn’t capture with the old version...

That’s the reason why I need to have access to the devices myself.. only option to learn this is by using a Zigbee sniffer and Wireshark... 
Homey’s logging is insufficient for this...

**Comment by dkduck** [comment]
@TedTolboom  I actually decided to order one for you when I got home if you didn´t had one.
Next time I order something and if you don´t have the device, I´ll order an extra to sent to you, that way I can show my appreciation and get things done LOL

Happy easter and yet again, thanks for you dedication and service :-)

**Comment by TedTolboom** [comment]
@dkduck thanks... appreciate the gesture.

Happy easter!
