### ISSUE TITLE
Work on r.11

### ISSUE THREAD

**Issue by Maxwell70** [TedTolboom/com.xiaomi-mi-zigbee#39]
After updating to r.11 it is impossible to add devices to the Homey!

**Comment by TedTolboom** [comment]
@Maxwell70 can you update Homey's SW to 1.5.6 (currently in experimental), perform a reboot and verify if this resolves the issue

**Comment by Maxwell70** [comment]
@TedTolboom 
I set 1.5.6. It didn't solve the problems! When you add a new device, the result is: "Device not found" or "requires device reset" or the label "Device added" appears, followed by "Device not found".

**Comment by TedTolboom** [comment]
How many battery powered (end-point) and non-battery powered (router) Zigbee devices do you now have included?

**Comment by Maxwell70** [comment]
@TedTolboom 
Currently added (added before new year):
![2](https://user-images.githubusercontent.com/33258356/36246921-82142778-1264-11e8-8d6f-18c462d8ca81.PNG)
![3](https://user-images.githubusercontent.com/33258356/36246934-8b158d1c-1264-11e8-97fe-24e210b3586d.PNG)

**Comment by TedTolboom** [comment]
@Maxwell70 do you still experience this issue (also after a reboot / removing the device before re-adding)?

**Comment by Maxwell70** [comment]
@TedTolboom unfortunately, Yes

**Comment by Maxwell70** [comment]
I currently have 20 devices in the Homey.

**Comment by Maxwell70** [comment]
@TedTolboom Hi! After updating to 0.3.0 I tried to add devices to Homey - it is impossible! I tried Aqara Human Body Sensor, Aqara Temperature and Humidity Sensor, Aqara Smart Socket ZigBee Version, Aqara Wireless Remote Switch Double. I couldn't add anything.

**Comment by jwikman** [comment]
@Maxwell70 I think that you've hit the roof on how many Zigbee devices that can be directly connected to Homey. I've read somewhere that the limit is 20 devices. I've had issues with this myself before, and the solution was to add Zigbee devices that can act as routers. To be able to act as a router it has to be connected to power, ie. not running on battery. In that way battery powered devices can communicate with Homey through the Zigbee router.
I've been using IKEA Trådfri light bulbs as routers. To be able to add a ligth bulb, you first need to remove some other device, making room for the new device within the 20 device limit. When you later see that some battery powered devices communicates through your light bulb, you can add more devices... I hope that helps.

**Comment by jwikman** [comment]
@maxwell70 sorry, I didn't see your screenshot before... But then the issue must be that no device are using the routers. I don't know how to force a device to go through a router, it just happens for me.. it might be related to how all devices are located... 
I cannot understand why there's a hard limit of only 20 devices, 20 devices are not many IMO.

**Comment by kasteleman** [comment]
The hard limit to 20 devices without a router is a limit in the hardware of
the devices. That is not a application limit, nor is it a specific limit of
Homey. It is part of the Zigbee specs. Some brands have a higher limit, but
that is the choice of that brand.

Op za 5 mei 2018 om 09:15 schreef Johannes Wikman <notifications@github.com>

**Comment by kasteleman** [comment]
There are a few ways to try to get devices use the router instead of a
direct connection:

1. Reboot Homey. After a reboot wait for a few minutes. The mesh wil
rebuild and can lead to a different route of Some devices

2. Try to include a device near to a router and at the spot at the final
location of the device. Although Some devices are picky and a inclusion
won’t succeed. That’s trial and error...

Last thing is, that in adding i routers,  you add another i x 20+
(depending on the brand) possible connections. However if you include
nearby Homey, the device wil always try to connect directly to Homey and
thus could fail.

Op za 5 mei 2018 om 09:44 schreef Johannes Wikman <notifications@github.com>

**Comment by Maxwell70** [comment]
@kasteleman @jwikman I have 4 routers. For a long time on old firmwares Routers were routers for other devices! And then after the update it disappeared! Homey firmware is to blame for these limitations! I have more than 50 devices on Mihub and everything works fine.

**Comment by Maxwell70** [comment]
@kasteleman I tried that already.

**Comment by kasteleman** [comment]
@Maxwell70 from what firmware did that happen? Did you put in a issue at
Athom’s github or mailde support?

Op za 5 mei 2018 om 10:04 schreef Maxwell70 <notifications@github.com>

**Comment by Maxwell70** [comment]
@kasteleman 
In January was so:
<img width="676" alt="2018-01-19 18 33 12" src="https://user-images.githubusercontent.com/33258356/39661134-d9356210-5076-11e8-8d94-87fac0c9a537.png">
And now here is so:
<img width="617" alt="2018-01-28 10 33 06" src="https://user-images.githubusercontent.com/33258356/39661145-17a46a64-5077-11e8-8d35-a0b0f94bc97d.png">
In support of a lot about it wrote!

**Comment by kasteleman** [comment]
@Maxwell70, they removed the picture for a reason: it wasn’t always correct.

If i would trust that, i would panic right away 😉

Op za 5 mei 2018 om 10:20 schreef Maxwell70 <notifications@github.com>

**Comment by Maxwell70** [comment]
@kasteleman Should I upgrade to Version 1.5.11-rc.1?

**Comment by jwikman** [comment]
@maxwell70 I'm running 1.5.11-rc1, and at least some devices are meshing...
(btw, I want that illustrative mesh map back as well)

**Comment by Maxwell70** [comment]
@jwikman Updated. Let's wait and see ......

**Comment by Maxwell70** [comment]
@jwikman I removed one sensor from Homey. Then I wanted to pair the Smart socket plug with Homey - "Device not found"!

**Comment by Maxwell70** [comment]
@jwikman Hi! I bought some light bulbs IKEA Trådfri. Paired them with Homey. After that, I was able to add more devices to the Homey. But after some time, long-added devices stop working.
