### ISSUE TITLE
Enhancement Request: Calibration value for sensors

### ISSUE THREAD

**Issue by MagnusPer** [TedTolboom/com.xiaomi-mi-zigbee#43]
My [Aqara](https://xiaomi-mi.com/sockets-and-sensors/aqara-temperature-and-humidity-sensor/) temperature sensors are not that accurate. Would be nice to be able to add an calibration value +/- (example -2.8 degree)

As referense the [Wireless Weather Station](https://apps.athom.com/app/com.weather-sensors) has this feature!

**Comment by TedTolboom** [comment]
Hi @MagnusPer yes this should be possible to add...
I'll add it in one of the next updates.

**Comment by TedTolboom** [comment]
Added in v0.2.5 for both temperature / humidity sensors (only for temperature) 
I'll close this issue... please re-open if not working properly / not to your expectation

**Comment by MagnusPer** [comment]
Sorry for late feedback - the calibration feature works great. Thanks for the update!
