### ISSUE TITLE
[Req] New Flow card : Open or Closed

### ISSUE THREAD

**Issue by Radiotechniman** [TedTolboom/com.xiaomi-mi-zigbee#44]
My request is to include a "Open OR Closed" flow card 
This would allow us to use the "Else" part of a flow cutting down the needed flows by 50% 
e.g; 
IF "Door Open" THEN   "Send Notification "Door Open""
IF "Door Closed" THEN  "Send Notification "Door Closed""

Would become: 
IF "Door Open or Closed" AND Door Open THEN  Send Notification "Door Open" ELSE Send Notification "Door Closed"

I had put this initially on the forum, but somoen mentioned the github would be better 

https://forum.athom.com/discussion/4766/req-flow-card-contact-open-or-closed?new=1

**Comment by TedTolboom** [comment]
@Radiotechniman fully support the feedback of @m-ruiter in https://github.com/mruiter/com.neo/issues/48 ...

It doesn't make sense to build this standard functionality separately in several apps.
I would advice to create an issue at https://github.com/athombv/homey/issues

**Comment by Radiotechniman** [comment]
Yes, i agree and have already created a ticket
https://github.com/athombv/homey/issues/2296

thanks for the support


‌
<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

2018-03-05 17:04 GMT+01:00 dT <notifications@github.com>:
