### ISSUE TITLE
Stuck in crash loop

### ISSUE THREAD

**Issue by chinswain** [TedTolboom/com.xiaomi-mi-zigbee#46]
I just noticed none of my devices are working, looks like a crash loop?

`Stack trace: (node:1346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit /drivers/sensor_86sw1lu/device.js:23 .then(() => { ^ TypeError: this.onOnOffListener.bind(...).then is not a function at AqaraLightSwitchSingle.onMeshInit (/drivers/sensor_86sw1lu/device.js:23:5) at AqaraLightSwitchSingle.once (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:51:28) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:106:13) at AqaraLightSwitchSingle.emit (events.js:208:7) at process.nextTick (/node_modules/homey-meshdriver/lib/MeshDevice.js:43:11) at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback (internal/process/next_tick.js:180:9) Exit code: 1 Exit signal: null`

**Comment by chinswain** [comment]
Here's the log when running from cli:

`(node:14067) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit
2018-03-06 16:59:35 [log] [XiaomiZigbee] Xiaomi Zigbee app is running...
2018-03-06 16:59:35 [log] [ManagerDrivers] [cube] [0] ZigBeeDevice has been inited
2018-03-06 16:59:36 [log] [ManagerDrivers] [sens] [0] ZigBeeDevice has been inited
2018-03-06 16:59:36 [log] [ManagerDrivers] [sensor_86sw1lu] [0] ZigBeeDevice has been inited
/drivers/sensor_86sw1lu/device.js:23
                        .then(() => {
                         ^

TypeError: this.onOnOffListener.bind(...).then is not a function
    at AqaraLightSwitchSingle.onMeshInit (/drivers/sensor_86sw1lu/device.js:23:5)
    at AqaraLightSwitchSingle.once (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:51:28)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at AqaraLightSwitchSingle.emit (events.js:208:7)
    at process.nextTick (/node_modules/homey-meshdriver/lib/MeshDevice.js:43:11)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

--- INFO: com.xiaomi-mi has been killed ---
`

**Comment by SadhuRus** [comment]
A have this problem too

**Comment by chinswain** [comment]
Do you have Aqara Light Switch Single? I've removed this and it's working. If you try and add it back it breaks again.

**Comment by TedTolboom** [comment]
Thanks for the logging!

Ok... I see the (copy-paste) error I made... apologies for that.
Seems to be limited to the Aqara Light Switch Single. Will check other devices as well

Will update the code this evening and push the update to the App Store later this evening.

**Comment by chinswain** [comment]
@TedTolboom I'll test as soon as it's up here - The house is in darkness! :)

**Comment by TedTolboom** [comment]
Well I don't want to leave you in the dark... worked on the fix first....

Can you test if this update (development branch) solved the issue:
https://github.com/TedTolboom/com.xiaomi-mi-zigbee/tree/development

Thanks!

**Comment by chinswain** [comment]
@TedTolboom  Fixed! Although only 1x click scene is showing in the Scene has been activated card?

**Comment by TedTolboom** [comment]
Thanks for the feedback.
On the 1x click, well... the changelog says it all:
> Fix issue where unsupported options are presented in the trigger card of the Aqara Wireless Remote Switch Single, related to #37

Still on the featurelist though to implement the additional options
