### ISSUE TITLE
Add support for xiaomi Gateway, for network-extension purpose

### ISSUE THREAD

**Issue by mauritsivs** [TedTolboom/com.xiaomi-mi-zigbee#48]
since the gateway has no function anymore now that homey has taken over, it would be nice to use the zigbee connection of the gateway to be able to extend the zigbee signal.
and possibly also use the light, speaker and luminance sensor on the gateway?

**Comment by TedTolboom** [comment]
@mauritsivs see my response on the forum: https://forum.athom.com/discussion/comment/69059/#Comment_69059

> @mauritsivs said:
> Any chance the Xiaomi gateway will be added to the app, to at least have it function as a sort of zigbee-network extender, 
> and maybe the other functions like the light, sound and luminance sensor can be used with zigbee? (if thats at all possible)
> No. Adding a Xiaomi gateway (there are multiple versions), is only possible over wifi.
> As far as I'm aware the gateway does not support to be included via Zigbee on other Zigbee networks. 
> Therefore it will not act as a Zigbee network extender... For that use, I would recommend the Plug instead.
