### ISSUE TITLE
"1x click" scene triggers for switches on 0.2.4 are broken

### ISSUE THREAD

**Issue by synegic** [TedTolboom/com.xiaomi-mi-zigbee#50]
Hello,

All my switches' scene flows are triggered by the "1x clicked" flow card. This was done with the hope that in the future multi-click would become possible and therefor not having to change everything from "A button has been pressed" to "x times clicked". However, since the latest update (v0.2.4 at time of writing) all these flows using the "1x clicked" trigger do not work anymore. If I change the flow 'if' card to "A button has been pressed", it starts working again.

Maybe this has something to do with the removal of the 2x/3x/4x click trigger options? The switch itself is fine, I also tried re-including the switch by deleting it and re-adding, but that didn't work in my case.

**Comment by TedTolboom** [comment]
@synegic eventhough not mentioned it explictly, I expect that the device in question is the Aqara Wireless Remote Switch Single. Correct?

**Comment by synegic** [comment]
That is correct. I actually have both single and double switches in use, the single ones have the above issue. The double ones work fine with the 1x clicked trigger (as in; left side; 1x clicked works for example), but the 'both clicked' trigger does not work there either.

**Comment by TedTolboom** [comment]
@synegic can you try with the new autocomplete scene flow triggers of the v0.3.0 app update?
And report back.

**Comment by TedTolboom** [comment]
Closed due to inactivity, please re-open if the issue persists
