### ISSUE TITLE
Aqara Temperature and Humidity Sensor stops updating after a few days

### ISSUE THREAD

**Issue by magtimmermans** [TedTolboom/com.xiaomi-mi-zigbee#51]
Hi,
I have one Aqara Temperature and Humidity Sensor and after a few days it stops updating the values. I have disconnected it again and attached it again to the zigbee network but after a few days the same happens again. I have version 0.2.4 and Homey Firmware Version: 1.5.8.

PS. Other devices Aqara Window/Door Sensor and Aqara Wireless Remote Switch Double are working great!

Could this be a device problem, homey or the app?

Thanks,

Marcel Timmermans

**Comment by TedTolboom** [comment]
Hi @magtimmermans,

I've heard more reports on (Xiaomi) Zigbee devices that stop reporting...
But it is quite difficult to pinpoint where the issue is originating from... Just checked my 2 sensors, and both are reporting continously...

Can you provide some more information:
- At what distance is the sensor located from Homey?
- Is the sensor in direct communication with Homey or communicating through a Zigbee router to Homey?
- Which Zigbee devices do you have connected? Can you post a screenshot of your Nodes overview (https://developer.athom.com/tools/zigbee)?
- When the device stops reporting... what happens when you hold the sensor in your hands (without pressing the button)?

**Comment by magtimmermans** [comment]
Sure.

1) The distance is 5 meter but a concrete wall between it.
2) Direct to Homey
3)
![2018-03-15 20_27_31-athom developer](https://user-images.githubusercontent.com/17949840/37486738-abf415f8-288f-11e8-82d8-c5b3f3d21e57.png)

4) Doesn't change. Even if I bring it close to Homey, it does not change.

**Comment by ljsvv** [comment]
I can confirm the exact same issue. Only have it with one and the same Aqara Human Body sensor. Bringing the device close to Homey doesn’t work. Only a re-add Works for a couple a of days and then the same problem comes back.

**Comment by mkmintman** [comment]
In response to the above comment, I bought this thing to put into my humidor with smartthings. As soon as it gets to 65% humidity it stops working.

**Comment by TedTolboom** [comment]
@magtimmermans @mkmintman there is no hard limit where the Aqara temperature and humidity sensor stops reporting the humidity...
I checked my own insights and tested it by using the sensor as a breath analyzer (rapidly increasing the temperature and humidity) and it responds instantly and well above the 60-65%... you could try this yourself.

Also today on Slack, the user @deadlifter posted this graph, showing humidity levels above 60-65%
![image](https://user-images.githubusercontent.com/17163431/38209062-5d7c5fa2-36b3-11e8-9e6f-6773d43e2456.png)

I don't think and cannot reproduce that it is related to a specific value... 
More related to a more generic instability of the Zigbee network; also reported at Athom for more (different) devices

**Comment by lubbertkramer** [comment]
Issue is bigger then only the humidy, more battery xiaomi devices lose connection over time. Have reported this at athom and discussed it with @TedTolboom but it doesn't looks like a app problem more a zigbee core problem

**Comment by magtimmermans** [comment]
Does anyone knows how to make sure they can reported again. I have rebooted the homey, remove battery from the Aqara Temperature and Humidity Senso and but it back. But all did not help. After 3-8 times removing the device from the network and added again it works. But then it looses all information and flows :( Any news?

**Comment by mgutierrezp** [comment]
Hi,

I'm also suffering this issue. Sensors (temperature, switch, wall plug, for example) disconnects after a few hours. They normally reconnects automatically, but some hours later, with no intervention. I'm not sure, but I think sensors reconnects automagically after some event occurs: door/window magnet opens, somebody clicks a button, etc. It's like they enter some kind of deep sleep and wake up again when something happens.

Any help/idea is appreciated!

Regards.

**Comment by TedTolboom** [comment]
@mgutierrezp as mentioned by @lubbertkramer this is a bigger issue that is originating out of Homey’s Zigbee core (outside my control)...
Many (different) devices (incl IKEA and HUE) suffer from the same issue...
As far as I know, there are no known containment’s...

Hopefully, Athom will deliver the Zigbee re-write (post 2.0) as soon as possible

**Comment by Ruugy** [comment]
Is there something new about the disconnecting Temperature Sensors?

**Comment by JustThe2ofUs** [comment]
Hi;
As it’s been a while (damn!) -
Is there any news, as I could kick all the sensors to trash can as they simply are useless when not updating their values anymore ?!?

**Comment by mickem** [comment]
I have had multiple devices stop working, buttons, temp, etc etc and what I do is "add them again", Homey will say "device already added" after which they all start working again (for a while).
Worth noticing is that it reoccurs with *the same devices* while other devices never have this issue so my guess is that it is a flaw in some devices now Homey/the app...
But re-adding them always seems to work...

**Comment by JustThe2ofUs** [comment]
Hiya, see 3 posts above as Ted mentioned this is an issue w/ Homeys Core re Zigbee.
I contacted Athom support directly, mentioning this statement here as well.
I´d suggest you to do the same as addressing the issue directly to Athom might help:
https://support.athom.com/hc/en-us/articles/360015784034-Submit-a-support-request

**Comment by magtimmermans** [comment]
Is it solved? I have still this issue every few weeks?

**Comment by mickem** [comment]
No it is not solved but I think the consensus is that the problem is with Homey not the app, so there is no bug in the app it self and nothing that can be done in the app to solve the issue...

**Comment by reinux** [comment]
I kind of wonder if maybe it needs a [Keep Alive notification](https://zigbeealliance.org/wp-content/uploads/2019/12/07-5123-06-zigbee-cluster-library-specification.pdf) (chapter 14.3) or something every now and then?

**Comment by markusv** [comment]
Are there any updates on this? I have the same problem with Aqara temperature sensors

**Comment by snorrehu** [comment]
> Are there any updates on this? I have the same problem with Aqara temperature sensors

x 2

I have this problem with all my aqara sensors, they stop reporting whenever humidity goes over a certain limit (seems to happen consistently at about 60-65%). Really annoying.

**Comment by rabw** [comment]
> > Are there any updates on this? I have the same problem with Aqara temperature sensors
> 
> x 2
> 
> I have this problem with all my aqara sensors, they stop reporting whenever humidity goes over a certain limit (seems to happen consistently at about 60-65%). Really annoying.

I am also having this issue with my Aqara temperature sensor.
