### ISSUE TITLE
Aqara double switch wireless

### ISSUE THREAD

**Issue by etretti** [TedTolboom/com.xiaomi-mi-zigbee#52]
Stopped working in latest release and i cant re pair Them either.

**Comment by TedTolboom** [comment]
@etretti can you give me a bit more information?
What did you try to do / what was the result? etc

**Comment by etretti** [comment]
I had it controlling 2 lights in My livingroom. They worked fine every Day til 1.5.8 then just stopped. And i cant repair Them. Homey never detects it. Just Times out. I dont know how to give you more then that ☹️ i havet not tried pairing it since i wrote the first post. Ill try again tonight.

**Comment by etretti** [comment]
Ok now ive tried to pair the old one and a new one, none of them gets paired. It either times out or after cluster grabbing says something went wrong. Other single button aqara buttons work and Philips Hue zigbee lampa work. Also tried to restart THE app and homey. Nothing helps.

**Comment by TedTolboom** [comment]
@etretti do they all work now? Can this issue be closed?

**Comment by etretti** [comment]
@tedtolboom yes i got the other one to work. Its a real pain to pair them but it eventually gets done. The pairing process with these är far from bugfree. U can Close.
