### ISSUE TITLE
Aqara Window/door switch (New one) not activating flows

### ISSUE THREAD

**Issue by canedje** [TedTolboom/com.xiaomi-mi-zigbee#54]
Homey flows do not pick up the changing contact status.
At the devices you see contact open or closed and changing
The flow is not reacting and picking up the change

It worked fine before

**Comment by canedje** [comment]
I did a PtP to Homey.
Now everything is fine again

**Comment by TedTolboom** [comment]
@canedje so the issue can be closed?
