### ISSUE TITLE
Не работают выключатели Aqara

### ISSUE THREAD

**Issue by Romast-Kirov** [TedTolboom/com.xiaomi-mi-zigbee#61]
Доброго времени!!!!
Насмотревшись видео в сети я решил построить свой "умный дом" на атоме.
Потихоньку купил датчики , сегодня пришли выключатели Aqara. 
И вот тут проблема , они добавляются,  но не реагируют не на какие действия с шарика, только физическое нажатие на выключатели работает. 
Если отключить Xiaomi Mi ZigBee и подключить выключатели просто как ZigBee то включение выключение работает.
Версия Xiaomi Mi ZigBee v0.3.0
Версия Атома 1.5.9
Зарание спасибо за помощь.

**Comment by TedTolboom** [comment]
@Romast-Kirov I don’t speak Russian; is this issue a duplicate of the new one you created: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues/63

If so, I would propose to close this ine
