### ISSUE TITLE
Xiaomi Cube Double Tap don't work

### ISSUE THREAD

**Issue by ca5perl** [TedTolboom/com.xiaomi-mi-zigbee#62]
Hello. 

I have successfully pair there mi cube and all are working except double tap and motion.

Anyone can help?

**Comment by TedTolboom** [comment]
Hi @ca5perl,

Can you clarify which ‘motion’ you mean? Sliding?

Perhaps the answer to the issue: double taping (and also sliding) has to be done with the cube and not on the Cube...

so in case of double tapping, you’ll need to lift the Cube and knock twice on e.g. the table surface. Not tapping twice on the Cube itself...

**Comment by chinswain** [comment]
@ca5perl Double tap and slide works fine for me.

**Comment by TedTolboom** [comment]
Closed due to inactivity, please re-open if the issue persists
