### ISSUE TITLE
Mi lumi plug not logging energy measurement anymore

### ISSUE THREAD

**Issue by koktaildotcom** [TedTolboom/com.xiaomi-mi-zigbee#65]
Expected Behavior:
The energy measurement is shown in the `device card` and in `insights`.

Current Behavior:
The energy measurement is not shown in the `device card` and in `insights`. After a couple of days the energy measurement of the device stops working. The current `power` is `0` and not updated anymore.

Running: 
Homey 1.5.11-rc1 on the latest app firmware.

**Comment by koktaildotcom** [comment]
Someone with the same issue?

**Comment by TedTolboom** [comment]
@koktaildotcom I will try to reproduce in the next days...

Can you try if a reboot (including re-init) solves the issue? It might be caused by a generic Zigbee bug.

**Comment by koktaildotcom** [comment]
A reboot and repair does not solve the issue. I've have a flow that verifies every 5 minutes to turn on an ikea vaxer (hydro plant) based on luminous intensity and time. Yesterday i've switched on the socket manualy, and thereby the energy measurement came back at ones. Is there a difference between a flow trigger or a manual one?

**Comment by koktaildotcom** [comment]
Today i noticed that the energy measurement is not logged anymore.

**Comment by koktaildotcom** [comment]
![image](https://user-images.githubusercontent.com/10741929/40478914-a35f1a90-5f4a-11e8-9dfa-3405558709a7.png)

**Comment by koktaildotcom** [comment]
This is still an issue. Is this related to zigbee rewrite? Is there a possibility to reset the energy measurement?
