### ISSUE TITLE
Can't add more devices

### ISSUE THREAD

**Issue by webinfodk** [TedTolboom/com.xiaomi-mi-zigbee#67]
I have pared 24 xiaomi devices and now I can't add more, as i read there should be no limidt.
[homeu zigbee devices.txt](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/files/2024101/homeu.zigbee.devices.txt)

**Comment by permadm** [comment]
I have paired 25 xiaomi/aqara zigbee devices and now I can't add more ((( 
How can this problem be solved?
