### ISSUE TITLE
Philips Light bulb adding error

### ISSUE THREAD

**Issue by kopanicak** [TedTolboom/com.xiaomi-mi-zigbee#71]
i can't add Philips light bulb.
i have got an error: device.power is not a function.
IP and token are good.

what i do wrong? thanks

![screen](https://user-images.githubusercontent.com/9351901/40990623-b9bc5b30-68f1-11e8-8676-88a64a1db5e6.png)

**Comment by TedTolboom** [comment]
@kopanicak this is an issue not related to the Xiaomi Zigbee app, but to the Xiaomi Mi Home app. 
I suggest to create an issue for additional support at https://github.com/jghaanstra/com.xiaomi-miio

Will close this one since it is not the scope of this app
