### ISSUE TITLE
Doesn't work properly with more then 20 devises (Atom)

### ISSUE THREAD

**Issue by AlekseyAE** [TedTolboom/com.xiaomi-mi-zigbee#72]
I add 24 devises and now after delay (5+ hours) nothing work. 
After reboot Athom everything work again, but after a little delay - nothing work again.

**Comment by PabloRuis** [comment]
I`ve got  the same problem....

**Comment by TedTolboom** [comment]
@AlekseyAE @PabloRuis can you post a screenshot of your Nodes overview from: https://developer.athom.com/tools/zigbee?
In the current Zigbee implementation of Homey, there are limitations with the amount of (batttery powered) Endpoints you can add (vs the amount of Routers).

**Comment by PabloRuis** [comment]
@TedTolboom 
<img width="653" alt="img1" src="https://user-images.githubusercontent.com/41194052/42733337-8a88b654-8838-11e8-9e52-cf130a793a06.PNG">
<img width="650" alt="img2" src="https://user-images.githubusercontent.com/41194052/42733338-8aaf5444-8838-11e8-855b-bb451961b8c0.PNG">
<img width="655" alt="img3" src="https://user-images.githubusercontent.com/41194052/42733339-8ad1f51c-8838-11e8-96ab-4a1e5c03640e.PNG">
