### ISSUE TITLE
Adjust sensitivity of Aqara Cube - add feature

### ISSUE THREAD

**Issue by YD85** [TedTolboom/com.xiaomi-mi-zigbee#76]
I've just installed Homey and am experimenting with the Aqara Cube to control curtains, lights and sonos. However the Cube response too sensitive on any movement; i.e. command movement or shake. Result when a turn in bed (Cube is next to my bed) the curtains open, lights turn on and music starts playing... not a favourable scenarios.
It would be good if you can set tresholds for sensors (not only for the Cube btw).

Thanks a lot for looking into this! Please let me know if you need any more input.

**Comment by TedTolboom** [comment]
@YD85 I'm not aware that the Cube provides options to set the sensitivity of the build in sensors...
So this is a device feature / limitation for which I don't see options to solve it from driver / app side.

You could try to change movement type to 90 degrees flipped or double tap to prevent accidental triggers. Or build in an additional condition to only switch on the light / music if the movement occurs between 06:00 and 10:00...

**Comment by TedTolboom** [comment]
thanks for the feedback! I'll close this issue for now.
