### ISSUE TITLE
Aqara human body sensor & occupancy sensor don`t work correctly

### ISSUE THREAD

**Issue by PabloRuis** [TedTolboom/com.xiaomi-mi-zigbee#77]
The sensors worked perfectly whith milia app, but whith Homey they dont`t work  stably. How can I fix this?

Thx!

**Comment by TedTolboom** [comment]
@PabloRuis can you provide more information to understand the issue better?
What is your setup / Homey version / app version?
When does the issue occur and what is the issue (not triggering / not updating)?

**Comment by PabloRuis** [comment]
@TedTolboom 
Homey version 1.5.11 (windows 10)
Sorry, I didn`t correctly identify the problem. The sensors work normaly, but  the scene (sensor - wall switch or sensor - light bulb) runs with delay or doesn`t work. Sometimes everythink works fine, but it doesn`t happen often.
