### ISSUE TITLE
Using without Xiaomi bridge. 

### ISSUE THREAD

**Issue by kapusticka** [TedTolboom/com.xiaomi-mi-zigbee#79]
Hi. It’s possible to use Xiaomi home sensors without bridge? It’s possible  connect itvto Athom Homey directly?

**Comment by TedTolboom** [comment]
That’s the whole purpose of this app...

**Comment by robinbakkenes** [comment]
Hi Kapusticka, 

Yeah, thats possible you can add all devices mentioned in the supported section without using a bridge. GL!

**Comment by TedTolboom** [comment]
closing the issue; questions answered
