### ISSUE TITLE
[Feature Request] Add temperature to door/window sensor

### ISSUE THREAD

**Issue by circuuz** [TedTolboom/com.xiaomi-mi-zigbee#80]
The door and window sensor also measures temperature. Deconz for example seems to have found a way to fetch this. 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-sensors

Can we do the same?

**Comment by TedTolboom** [comment]
@circuuz yes, that would be possible if Athom will make a change in the Zigbee core...

It requires a manufacturing specific attribute to be provided unparsed... currently the report is parsed and therefore unreadable.
This is the same attribute also providing the battery information of the device (on an hourly interval).
https://github.com/athombv/homey/issues/2165

I would not expect that Athom will fix this ahead of the Zigbee re-write (post 2.0 deliverable).

**Comment by circuuz** [comment]
I see, thank you for the clear answer.

tors 30 aug. 2018 kl 10:30 skrev dT <notifications@github.com>:

**Comment by pendragon1** [comment]
Any news on this? I know that the square sensor is showing battry info, the round one doesn't. Temperature would be great as well!

**Comment by TedTolboom** [comment]
Temperature is proven not to be reliable enough. I will not add this data; will lead to too many questions
