### ISSUE TITLE
Xiaomi Aqara Zigbee Shock Sensor not supported

### ISSUE THREAD

**Issue by YD85** [TedTolboom/com.xiaomi-mi-zigbee#81]
Dear developer, fellow Homey fan,

I bought the Xiaomi Aqara Zigbee Shock Sensor, but unfortunately the device is not available in the app. Could you please add this device?
Thank will be highly appreciated!

Thanks,
YD85

**Comment by TedTolboom** [comment]
Hi @YD85 
I’m working to reverse engineer the data provided by the Aqara Vibration sensor (official name).. already found some additional options that are not supported by the Xiaomi hub itself.

Will need to finalize the driver and some artwork...
So working on it.

Regards, Ted

**Comment by YD85** [comment]
Thanks a lot Ted! That is much appreciated!

Groet,
Yves

**Comment by Emile86** [comment]
I bought few of them, will be great if you can add them.

Many thanks for your work!

**Comment by TedTolboom** [comment]
Will be solved in v0.4.2

**Comment by TedTolboom** [comment]
v0.4.2 has been uploaded to the app store, awaiting Athom's approval.
I will close this issue.

**Comment by YD85** [comment]
Hi Ted,

That is marvellous, thanks for the hard work!

Groet,
Yves
