### ISSUE TITLE
0.5c and 4% intervals for temp/humidity sensors

### ISSUE THREAD

**Issue by rasssta** [TedTolboom/com.xiaomi-mi-zigbee#83]
Hi,

I previously mentioned this in the app thread on the forum but thought it would be better to have it reported in an issue. So here's some copy paste from the initial post and the reply from Ted.

Q:
"I was previously using my Xiaomi temperature/humidity sensors connected directly to a Xiaomi GW and it had very specific updates, such as 0.03c and as often as every 5 seconds if there were major differences in temp/humidity. Now when I have them connected directly to Homey 99% of my updates are at 0.5c. For humidity it only updates if the value has changed more than 4%.

I did a comparison (same day and time frame) between my XiaomiGW+sensors setup and the Homey one, with outdoor sensors on both, and the Xiaomi GW stored 20 values within 18 hours, while Homey only stored 6 values."

A:
March 18
Time for some Q&A:
@rasssta @Brend Current Homey ZigBee implementation has a number of limitations, that currently block to update the attribute reporting parameters... 

I will check if, based on the communication between the Xiaomi gateway and the sensor itself, it is possible to optimize the reporting frequency (use the default frequency and threshold)...

**Comment by TedTolboom** [comment]
@rasssta Thanks for reporting (once more).
I will check once more if the communication between the sensor and the Xiaomi hub provides some additional insights...

**Comment by TedTolboom** [comment]
@rasssta can you check if v0.4.2 is improving... 
you might need to re-include the device or wake-up the device within 30 seconds of an app re-start

**Comment by rasssta** [comment]
Will test as soon as it's available.

**Comment by TedTolboom** [comment]
Just for reference the Insights data of one of my Aqara Temperature & Humidity sensors based on these settings:
[homey_device_Aqara Temperature & Humidity.measure_temperature.txt](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/files/2431820/homey_device_Aqara.Temperature.Humidity.measure_temperature.txt)

Some remarks:
* Insights only stores data if different to the previous data point; since data is stored with 1 decimal (2 decimal accuracy is not really relevant), several reports will not be visible in insights
* The sensor typically sends all three attributes (temperature, humidity and pressure) at the same time, so you could compare timestamps to see when reports are being received and not added to Insights.

**Comment by rasssta** [comment]
Hi there,

can you elaborate on "wake-up the device"? Just click on it so it flashes blue?

**Comment by TedTolboom** [comment]
yes, to ensure that the new / updated attribute report settings can be
received by the sensor...

**Comment by rasssta** [comment]
Does not seem to work. Running 0.4.2. I've

 rebooted the Homey to be sure.

* Removed one Aqara T/H/P sensor. Re-added. Still 0.5c intervals.
* I did the restart app followed by wake-up of device within 30 secs with the rest of my Temp/Humidity sensors but they are also showing 0.5c intervals

<img width="1221" alt="screenshot 2018-10-04 at 18 59 56" src="https://user-images.githubusercontent.com/4455235/46490235-bf067d80-c807-11e8-9c78-19e50e80f905.png">

**Comment by TedTolboom** [comment]
Thanks for the confirmation.

Without re-adding, it will be a bit tricky... you'll need to restart the Xiaomi app (to re-initiate the reportAttributeListener) and keep pressing the device button once every 2-4 seconds..

By keeping the device awake during the initiation of the app, the device will be awake when the new command (with the new settings) is being send by Homey.

**Comment by TedTolboom** [comment]
Did the round sensor loose it's Zigbee connection?
What happens if you press the button on the sensor?

**Comment by rasssta** [comment]
It flashes blue twice and the temp was updated to 22.6 on the round and 22.8 on the square.

**Comment by TedTolboom** [comment]
Curious if it now (re)starts sending updates..

**Comment by TedTolboom** [comment]
What is the current situation? Did the sensor start reporting again?

**Comment by rasssta** [comment]
The round one is still using "big" celsius intervals or very long time between updates, whereas the square reports 0.1 intervals with short intervals. I have 1 round and 1 square laying next to each other. I'll attach graphs.

Btw. How do I configure number of decimals in 0.4.3?

**Comment by rasssta** [comment]
Round:
<img width="1208" alt="screenshot 2018-10-30 at 12 08 44" src="https://user-images.githubusercontent.com/4455235/47714222-98880680-dc3c-11e8-9fed-a7f6aa15cfe0.png">
Square:
<img width="1208" alt="screenshot 2018-10-30 at 12 08 54" src="https://user-images.githubusercontent.com/4455235/47714223-98880680-dc3c-11e8-8797-b17a2d01c022.png">

**Comment by rasssta** [comment]
Works much better in Homey 2.0! I'll close this one now.

**Comment by rasssta** [comment]
Not sure why, but the round one is still using large intervals :(

**Comment by rasssta** [comment]
![image](https://user-images.githubusercontent.com/4455235/53719418-452dfb00-3e5e-11e9-9fd5-f14058523995.png)

**Comment by TedTolboom** [comment]
I can't further optimize in the current Zigbee core.
