### ISSUE TITLE
Request for Gyro/motion sensor DJT11LM

### ISSUE THREAD

**Issue by Joostzilla** [TedTolboom/com.xiaomi-mi-zigbee#84]
Hi Ted, is it possible to add support for the Motion Gyro sensor as described in the link?
Would be much appreciated

Best regards,
Joost Scholte

[https://www.aliexpress.com/item/Xiaomi-Aqara-Zigbee-Shock-Sensor-Mijia-Aqara-Smart-Motion-Sensor-Vibration-Detection-Alarm-Monitor-for-MiHome/32911954679.html](url)

**Comment by TedTolboom** [comment]
Hi Joost, 
I’m working to reverse engineer the data provided by the Aqara Vibration sensor (official name).. already found some additional options that are not supported by the Xiaomi hub itself.

Will need to finalize the driver and some artwork...
So working on it.

Regards, Ted

**Comment by Joostzilla** [comment]
Thank you very much Ted for your hard  an continued work for Homey

**Comment by TedTolboom** [comment]
Will be solved in v0.4.2

**Comment by TedTolboom** [comment]
v0.4.2 has been uploaded to the app store, awaiting Athom's approval.
I will close this issue.
