### ISSUE TITLE
Can't add Cube (zigbee device not found)

### ISSUE THREAD

**Issue by BrokenTable** [TedTolboom/com.xiaomi-mi-zigbee#85]
Hi,

I'm trying to add a Cube but the installation fail. After 20-30 seconds I get "Device will be added' (translated Dutch => English) but then after several minutes 'No Zigbee device found'. I keep pressing de reset/link button every 2 seconds and Homey and app is up to date.

Any thoughts?

**Comment by thjdeckers** [comment]
Same for me. I asked a colleague who also owns a Homey to test my Cube on his Homey and he WAS able to pair my Cube without problems.
Then he lent me his Cube to see if that would pair with my Homey and unfortunately that also doesn't pair on my Homey, so the Cube is no success for me until now.
Recently I have seen the exact same problem with a temperature sensor, while other sensors of the same type do pair without problems. Could be a faulty one, but I'm going to ask my colleague to test that one also.

**Comment by thjdeckers** [comment]
I'm not sure if it is related to that but I must admit that I have quite a large number of Zigbee nodes in my Homey network. I've been thinking about completely reinstalling it from scratch and registering the Cube as the first Zigbee device to see if that makes any difference but so far didn't have time for that.
One thing I noticed recently when I had to remove ~ 15 nodes that were not responding anymore the time to remove them significantly shortened the more I had removed. All have been added again and work fine for a week now, but no success with pairing the Cube.

**Comment by Emile86** [comment]
I have no problem with cube, it working just fine maybe reacting little bit slow.

**Comment by BrokenTable** [comment]
When I firts try te pair I got an 'Something went wrong' error. After that pairing didn't come further then the info page how to pair. Other Aqara devices also couldn't be paired anymore. After a 20 minute PTP pairde resulted again in an 'Something went...' ! haven only 11 Zigbee devices. Also asked on Homey Community but also without luck. Maybe different versions of the Cube?
