### ISSUE TITLE
Bug adding curtain 

### ISSUE THREAD

**Issue by igitlin** [TedTolboom/com.xiaomi-mi-zigbee#86]
I try to add my Aqara Curtain, but Homey add as Unknown ZigBee

my device 
LUMI
luni.curtain.es1
514
260

**Comment by TedTolboom** [comment]
@igitlin could you add a screenshot of the ID's (Devices > my device > settings > Device information) before and after a reboot of Homey?

And please mention the product Type as shown on the curtain controller itself.
