### ISSUE TITLE
Pairing instructions 

### ISSUE THREAD

**Issue by nhassink** [TedTolboom/com.xiaomi-mi-zigbee#87]
I found that when re-pairing a aqara window/door sensor the sensor started pairing after only a single button press instead of a 3sec press as mentioned in the pairing instruction. I had however reset the sensor with a 3 sec press before pairing it with the single press. Might be that in the reset state a single press is sufficient?

**Comment by robinbakkenes** [comment]
Hi nhassink, Same here. I also was able to add the sensor with a single click, as long as the sensor is reset prior to that.

**Comment by TedTolboom** [comment]
v0.4.3 solving this issue / feature request has been submitted to the app store
I will close this issue for now. Please re-open if not solved in v0.4.3
