### ISSUE TITLE
Unkown Aqara Wireless switch

### ISSUE THREAD

**Issue by Mustang1966** [TedTolboom/com.xiaomi-mi-zigbee#89]
Wireless switch is added as unknown device.

![img_20180922_090102](https://user-images.githubusercontent.com/43118018/45914686-c792a780-be48-11e8-94b9-b02175457e35.jpg)

![screenshot 2018-09-21 at 19 08 02](https://user-images.githubusercontent.com/43118018/45920659-fab85380-bea7-11e8-98c5-5b614c235e9b.png)

**Comment by TedTolboom** [comment]
@Mustang1966 can you show which ID's are shown in the device settings > device information?

**Comment by TedTolboom** [comment]
In #88 you did report to have the same ID's as in the screenshot you added (and removed):
https://user-images.githubusercontent.com/43118018/45895532-b6f31a80-bdd1-11e8-91c3-d5a39e40c8d6.png

But that is not corresponding to this device, correct?
So can you share the device information for this device? Thanks.

**Comment by Mustang1966** [comment]
Yes it was. Afterwards i realised that it was a issue about the remote switch.

Updated first post with screenshot,

**Comment by TedTolboom** [comment]
@Mustang1966 please see: https://community.athom.com/t/xiaomi-aqara-smart-home-zigbee-app-v0-4-1/156/57

**Comment by TedTolboom** [comment]
v0.4.3 solving this issue / feature request has been submitted to the app store
I will close this issue for now. Please re-open if not solved in v0.4.3

**Comment by TedTolboom** [comment]
v0.4.3 solving this issue / feature request has been submitted to the app store
I will close this issue for now. Please re-open if not solved in v0.4.3
