### ISSUE TITLE
Single switch does pair Homey but does not trigger any flows

### ISSUE THREAD

**Issue by C0wC0w** [TedTolboom/com.xiaomi-mi-zigbee#91]
Hey,

Today I added some Aqara double and single switches to Homey. The double switches work perfectly Unfortunately the single switch does not.

Paring the single switch with Homey works very smooth. After the succeeded pairing process the device information I see is:

![image](https://user-images.githubusercontent.com/43566521/46003613-3e31de00-c0b1-11e8-8504-97bf1630c9e9.png)

Now I want to include the single switch in an easy flow:

![image](https://user-images.githubusercontent.com/43566521/46003734-82bd7980-c0b1-11e8-8eca-83a4bb5ffde2.png)

Now the problem occurs. The light is not switching. If I test the flow by clicking the test button the light switches on and off.

Can anybody explain me what this could be or did I just found a bug?

Cheers

**Comment by TedTolboom** [comment]
@C0wC0w can you try with the `Een scene is geactiveerd` trigger card? 
So without the `VEROUDERD`; this one will be removed anyway in the next release.

At what distance wrt Homey do you use the device ?
Does it work when the device is at closer distance?

**Comment by C0wC0w** [comment]
@TedTolboom Are you kidding me!? haha that solved the issue. Thanks for your fast support :)

**Comment by TedTolboom** [comment]
Cool... will close this issue (and actually remove the old card in the next release)
