### ISSUE TITLE
lumi.ctrl_neutral2 (QBKG03LM) stops responding after a few times switching on/off

### ISSUE THREAD

**Issue by fantomnotabene** [TedTolboom/com.xiaomi-mi-zigbee#94]
Plugin v0.4.2 installed via cli.
Sometimes it (switch control via homey) works well, but time to time it unable to turn on or off. 
Log: <img width="1086" alt="2018-09-30 23 55 39" src="https://user-images.githubusercontent.com/9576189/46262801-27efac00-c50f-11e8-8067-5ea5755ff8a1.png">
And after several attempts it starts working again.
Other xiaomi-zigbee-devices not affected at all. Working as expected.

**Comment by fantomnotabene** [comment]
Restarting the application helps... for the first several minutes. 
Then it can fall off again. And then be available again without further action. 
BTW, 1.5.12, 6 zigbee-devices in all.

**Comment by TedTolboom** [comment]
@fantomnotabene thanks for reporting. 
v0.4.2 did not change anything in the implementation of the Aqara Smart Light Wall Switch (L) Double (QBKG03LM), so I don't expect that it is related to the update...

Considering the error code (coming back from the Homey core), it points towards a mesh issue / disturbance. 

Some follow-up questions:
At what distance is this switch installed compared to Homey?
Is there a meshroute available between this device and Homey?

Could it be some disturbance between Zigbee and WiFi networks interfering?

**Comment by fantomnotabene** [comment]
@TedTolboom, version just for the sake of clarifying as much detail as possible. 
3 meters in line of sight between the switch and Homey. No meshroute between them, direct connection.
Wi-fi router is (approximately) 4 meters in the other direction from Homey. Wi-fi channel 8, Zigbee - 11.

**Comment by fantomnotabene** [comment]
I used the network scanner on macOS and found that one of my neighbors (apartment building) is using the first wi-fi channel on his router and its signal is not much weaker than one of my own.
<img width="599" alt="2018-10-02 11 29 48" src="https://user-images.githubusercontent.com/9576189/46337807-291bf880-c637-11e8-91d7-21aa191c3111.png">
Is there any solution (without the need to interact with the neighbor's router) if exactly this thing cause the behavior described above?

**Comment by fantomnotabene** [comment]
Okay, I watched for a while what was going on here. So I don't think that the wi-fi/zigbee interference causes this. Problems show themselves with only one device. Closest device to Homey, described above, Aqara Wall Switch.
