### ISSUE TITLE
Vibration sensor triggering twice

### ISSUE THREAD

**Issue by chinswain** [TedTolboom/com.xiaomi-mi-zigbee#97]
The Vibration Alarm Turned On\Off cards are triggering twice when any vibration is started\stopped.
Is this expected behavior?

**Comment by TedTolboom** [comment]
@chinswain thanks for reporting... will be fixed in next release

**Comment by TedTolboom** [comment]
v0.4.3 solving this issue / feature request has been submitted to the app store
I will close this issue for now. Please re-open if not solved in v0.4.3

**Comment by chinswain** [comment]
Confirmed fixed!
