### ISSUE TITLE
Add a decimal to the temperature reported by the Aqara Temperature and Humidity Sensor (WSDCGQ11LM)

### ISSUE THREAD

**Issue by JohanBendz** [TedTolboom/com.xiaomi-mi-zigbee#98]
Hi Ted.
Would it be possible to add a decimal to the temperature reported by the Aqara Temperature and Humidity Sensor (WSDCGQ11LM) ?

The reason for this is that weather services require 2 decimals and several members of the Homey Homies community likes to send their info to the weather services temp sites.

**Comment by TedTolboom** [comment]
v0.4.3 solving this issue / feature request has been submitted to the app store
I will close this issue for now. Please re-open if not solved in v0.4.3
