### ISSUE TITLE
Aqara temperature sensor Unknown error

### ISSUE THREAD

**Issue by tatarrr95** [TedTolboom/com.xiaomi-mi-zigbee#99]
Aqara temperature and humidity sensor works about 6 hours and breaks. Write unknown error.

**Comment by navasm** [comment]
I also have a temperature and humidity sensor giving an 'Unkown Error'. 
After removing and readding I get 'Device has left the network, please remove and repair' after a couple of minutes. 
![device left network](https://user-images.githubusercontent.com/12073795/46908340-b73e8b80-cf21-11e8-95ed-f2b82c16cc9a.PNG)

**Comment by TedTolboom** [comment]
Can you (both) describe the situation / issue in a bit more detail?
Distance of the sensor to Homey? Other Zigbee routing devices that are providing a mesh network? etc

**Comment by tatarrr95** [comment]
The problem has disappeared after updating the plugin

**Comment by navasm** [comment]
The error with devices leaving are now gone. But I'm still having issues with sensors in a particular room (bathroom). The sensor works for about 3 days then it just stops reporting (temperature, humidity & pressure). There are no errors in Homey for this device! Another temperature sensor in a room adjacent to the bathroom sends data to Homey without any issues. These sensors are located on the first floor while Homey is on the groundfloor. The distance from the sensors to Homey is about 4-5 meters.
![temp sensors](https://user-images.githubusercontent.com/12073795/47770967-bc515800-dce1-11e8-9dac-21fb3b569ce6.png)
